Repository Migorithm/duva, pull requests merged in 2024-12, with the labels that each got.

#76 test: notify start up waiter
  src/lib.rs
  src/main.rs
  tests/common.rs
  tests/test_config_get_dir.rs
  tests/test_keys.rs
  tests/test_replication_info.rs
  tests/test_set_get.rs
Labels: testability

#77 chore: startup time added to config
  src/config.rs
  src/lib.rs
  src/services/statefuls/routers/cache_manager.rs
  src/services/statefuls/routers/mod.rs
Labels: enhancement

#79 feat: cancellation token
  src/adapters/cancellation_token.rs
  src/adapters/mod.rs
  src/lib.rs
  src/main.rs
  src/services/query_manager/interface.rs
  src/services/query_manager/mod.rs
  tests/common.rs
  tests/test_cancellation_token.rs
  tests/test_config_get_dir.rs
  tests/test_keys.rs
  tests/test_replication_info.rs
  tests/test_set_get.rs
Labels: enhancement, good first issue

#78 Refactor bytes encoder
  src/adapters/persistence/encoder/byte_encoder.rs
  src/adapters/persistence/encoder/encoding_processor.rs
  src/adapters/persistence/encoder/mod.rs
  src/adapters/persistence/mod.rs
  src/config.rs
  src/services/statefuls/routers/cache_actor.rs
  src/services/statefuls/routers/save_actor.rs
  tests/common.rs
  tests/test_config_get_dir.rs
  tests/test_keys.rs
  tests/test_replication_info.rs
  tests/test_save_read_dump.rs
  tests/test_set_get.rs
Labels: refactoring

#80 feat: spawn local set notification
  src/adapters/cancellation_token.rs
  src/lib.rs
  src/services/query_manager/interface.rs
  tests/common.rs
  tests/test_cancellation_token.rs
  tests/test_config_get_dir.rs
  tests/test_keys.rs
  tests/test_replication_info.rs
  tests/test_save_read_dump.rs
  tests/test_set_get.rs
Labels: enhancement

#90 feat: config manager
  src/config.rs
  src/lib.rs
  src/main.rs
  src/services/config/command.rs
  src/services/config/config_actor.rs
  src/services/config/config_manager.rs
  src/services/config/mod.rs
  src/services/config/replication.rs
  src/services/mod.rs
  src/services/query_manager/mod.rs
  src/services/statefuls/cache/cache_manager.rs
  tests/common.rs
  tests/test_cancellation_token.rs
  tests/test_config_get_dir.rs
  tests/test_handshake.rs
  tests/test_keys.rs
  tests/test_replication_info.rs
  tests/test_save_read_dump.rs
  tests/test_set_get.rs
Labels: enhancement

#94 feat: outline replication manager, connection factory
  dump.rdb
  src/adapters/io/tokio_stream.rs
  src/lib.rs
  src/main.rs
  src/services/config/config_actor.rs
  src/services/statefuls/cache/cache_actor.rs
  src/services/statefuls/cache/cache_manager.rs
  tests/common.rs
  tests/test_handshake.rs
Labels: good first issue

#98 enhancement: DI on endecoder
  src/adapters/endec/decoder/builder.rs
  src/adapters/io/tokio_file.rs
  src/adapters/mod.rs
  src/lib.rs
  src/main.rs
  src/services/query_manager/client_request_controllers/mod.rs
  src/services/query_manager/interface.rs
  src/services/query_manager/mod.rs
  src/services/statefuls/cache/cache_actor.rs
  src/services/statefuls/cache/cache_manager.rs
  src/services/statefuls/cache/ttl_manager.rs
  src/services/statefuls/persist/endec.rs
  src/services/statefuls/persist/endec/decoder/byte_decoder.rs
  src/services/statefuls/persist/endec/decoder/mod.rs
  src/services/statefuls/persist/endec/decoder/states.rs
  src/services/statefuls/persist/endec/encoder/byte_encoder.rs
  src/services/statefuls/persist/endec/encoder/encoding_processor.rs
  src/services/statefuls/persist/endec/encoder/mod.rs
  src/services/statefuls/persist/endec/mod.rs
  src/services/statefuls/persist/mod.rs
  src/services/statefuls/persist/persist_actor.rs
  src/services/statefuls/persist/save_actor.rs
  tests/common.rs
  tests/test_save_read_dump.rs
Labels: enhancement

#103 refactor: startup facade
  src/lib.rs
  src/main.rs
  src/services/config/config_actor.rs
  tests/common.rs
Labels: enhancement

#105 fix: ignore test that's not ready yet
  tests/test_handshake.rs
Labels: testability

#107 feat: handshake enum added, temporal coupling specified
  src/adapters/cancellation_token.rs
  src/adapters/io/tokio_file.rs
  src/adapters/io/tokio_stream.rs
  src/lib.rs
  src/services/config/config_actor.rs
  src/services/mod.rs
  src/services/query_manager/replication_request_controllers/replication_request.rs
  src/services/statefuls/cache/cache_actor.rs
  src/services/statefuls/cache/cache_manager.rs
  src/services/statefuls/persist/endec/encoder/encoding_processor.rs
  src/services/statefuls/persist/persist_actor.rs
  src/services/stream_manager/client_request_controllers/arguments.rs
  src/services/stream_manager/client_request_controllers/client_request.rs
  src/services/stream_manager/client_request_controllers/mod.rs
  src/services/stream_manager/error.rs
  src/services/stream_manager/interface.rs
  src/services/stream_manager/mod.rs
  src/services/stream_manager/query_io.rs
  src/services/stream_manager/replication_request_controllers/arguments.rs
  src/services/stream_manager/replication_request_controllers/mod.rs
  src/services/stream_manager/replication_request_controllers/replication_request.rs
  tests/common.rs
  tests/test_cancellation_token.rs
Labels: enhancement, feat

#108 feat: immuts values on config manager
  src/lib.rs
  src/main.rs
  src/services/config/command.rs
  src/services/config/config_actor.rs
  src/services/config/config_manager.rs
  src/services/config/macros.rs
  src/services/config/mod.rs
  tests/common.rs
  tests/test_save_read_dump.rs
Labels: enhancement, feat

#110 feat: peer information dissemination
  src/adapters/io/tokio_file.rs
  src/adapters/io/tokio_stream.rs
  src/lib.rs
  src/services/statefuls/persist/endec/encoder/encoding_processor.rs
  src/services/stream_manager/error.rs
  src/services/stream_manager/interface.rs
  src/services/stream_manager/mod.rs
  src/services/stream_manager/query_io.rs
  src/services/stream_manager/replication_request_controllers/mod.rs
  src/services/stream_manager/replication_request_controllers/replication_request.rs
  tests/common.rs
  tests/test_disseminate_peers.rs
  tests/test_handshake.rs
Labels: feat

#117 feat: cluster manager outlined
  src/adapters/io/tokio_stream.rs
  src/lib.rs
  src/main.rs
  src/services/cluster/actor.rs
  src/services/cluster/mod.rs
  src/services/config/command.rs
  src/services/config/config_actor.rs
  src/services/config/config_manager.rs
  src/services/mod.rs
  src/services/stream_manager/interface.rs
  src/services/stream_manager/mod.rs
  src/services/stream_manager/replication_request_controllers/mod.rs
  tests/common.rs
  tests/test_cancellation_token.rs
  tests/test_config_get_dir.rs
  tests/test_disseminate_peers.rs
  tests/test_handshake.rs
  tests/test_heartbeat.rs
  tests/test_heartbeat_broadcasting.rs
  tests/test_keys.rs
  tests/test_replication_info.rs
  tests/test_save_read_dump.rs
  tests/test_set_get.rs
Labels: enhancement, refactoring, feat

#120 feat: add peer outlined
  src/adapters/io/tokio_stream.rs
  src/lib.rs
  src/services/cluster/actor.rs
  src/services/cluster/command.rs
  src/services/cluster/manager.rs
  src/services/statefuls/cache/ttl/manager.rs
  src/services/stream_manager/interface.rs
  src/services/stream_manager/mod.rs
  src/services/stream_manager/request_controller/client/mod.rs
  src/services/stream_manager/request_controller/replica/arguments.rs
  tests/test_handshake.rs
  tests/test_heartbeat.rs
Labels: feat

#121 feat: add peer & heartbeat
  src/adapters/io/tokio_stream.rs
  src/services/cluster/actor.rs
  src/services/cluster/command.rs
  src/services/cluster/manager.rs
  src/services/stream_manager/interface.rs
  tests/common.rs
Labels: feat

#122 fix: client port assumption
  src/adapters/io/tokio_stream.rs
  src/lib.rs
  src/services/cluster/actor.rs
  src/services/cluster/manager.rs
  src/services/config/manager.rs
  src/services/stream_manager/interface.rs
  tests/common.rs
  tests/test_disseminate_peers.rs
  tests/test_heartbeat.rs
  tests/test_heartbeat_broadcasting.rs
Labels: bug, testability

#123 feat: test code refined for better testability
  tests/common.rs
  tests/test_disseminate_peers.rs
  tests/test_heartbeat.rs
  tests/test_heartbeat_broadcasting.rs
Labels: testability, feat
