Repository Migorithm/duva, pull requests merged in 2025-03, with the labels that each got.

#312 documentation on term, watermark
  diagrams/raft(3) - why_term.mmd
  diagrams/raft(4) - term_enable_conflict_resolution.mmd
  diagrams/raft(5) - commit based on hwm.mmd
  diagrams/raft(6) - discard based on hwm.mmd
Labels: documentation

#313 doc: idempotent receiver
  diagrams/raft(6) - discard based on hwm copy.mmd
  diagrams/raft(7) - idempotent receiver.mmd
Labels: documentation

#317 rename: commit idx to high water mark
  README.md
  diagrams/full_sync_scenario_snapshot.mmd
  diagrams/full_sync_scenario_with_append_entry.mmd
  diagrams/full_sync_when_commit_was_made.mmd
  diagrams/partial_sync.mmd
  src/domains/cluster_actors/actor.rs
  src/domains/cluster_actors/commands.rs
  src/domains/cluster_actors/replication.rs
  src/domains/query_parsers/query_io.rs
  src/lib.rs
  src/presentation/clients/controllers/handler.rs
  src/presentation/cluster_in/connection_manager.rs
  src/presentation/cluster_in/outbound/stream.rs
  src/services/handlers/cluster.rs
Labels: refactoring

#318 refactor: cache manager becomes a part of handle method
  src/domains/cluster_actors/actor.rs
  src/lib.rs
  src/services/handlers/cluster.rs
Labels: refactoring

#324 refactor: unnest peer kind
  src/domains/cluster_actors/actor.rs
  src/domains/cluster_listeners/mod.rs
  src/domains/peers/connected_types.rs
  src/domains/peers/peer.rs
Labels: refactoring

#326 feat: cluster nodes
  nodes
  src/domains/cluster_actors/actor.rs
  src/domains/cluster_actors/replication.rs
  src/domains/peers/identifier.rs
  src/domains/peers/kind.rs
  src/domains/peers/peer.rs
  src/presentation/cluster_in/connection_manager.rs
Labels: testability, refactoring, feat

#327 feat: peer follower & peer leader
  src/domains/cluster_actors/actor.rs
  src/domains/cluster_actors/replication.rs
  src/domains/peers/connected_peer_info.rs
  src/domains/peers/kind.rs
  src/domains/peers/mod.rs
  src/domains/peers/peer.rs
  src/lib.rs
  src/presentation/cluster_in/connection_manager.rs
  src/presentation/cluster_in/inbound/stream.rs
  src/presentation/cluster_in/outbound/response.rs
  src/presentation/cluster_in/outbound/stream.rs
Labels: refactoring, feat

#328 refactor: may try fullsync
  src/domains/peers/connected_peer_info.rs
  src/domains/peers/kind.rs
  src/presentation/cluster_in/connection_manager.rs
  src/presentation/cluster_in/inbound/stream.rs
  src/presentation/cluster_in/outbound/stream.rs
Labels: refactoring

#330 feat: cluster nodes client api
  src/domains/cluster_actors/commands.rs
  src/domains/query_parsers/query_io.rs
  src/presentation/clients/controllers/handler.rs
  src/presentation/clients/request.rs
  src/presentation/clients/stream.rs
  src/presentation/cluster_in/communication_manager.rs
  src/services/handlers/cluster.rs
Labels: feat

#337 fix: close client connection on abrupt disconnection
  scripts.sh
  src/adapters/io/tokio_stream.rs
  src/domains/error.rs
  src/presentation/clients/controllers/acceptor.rs
  src/presentation/clients/stream.rs
  src/presentation/listeners/leader.rs
  src/services/interface.rs
Labels: bug, refactoring

#338 chore: error spec further articulated
  src/actor_registry.rs
  src/adapters/io/tokio_stream.rs
  src/domains/caches/actor.rs
  src/domains/caches/cache_manager.rs
  src/domains/cluster_listeners/mod.rs
  src/domains/config_actors/config_manager.rs
  src/domains/peers/peer.rs
  src/domains/saves/endec/decoder/byte_decoder.rs
  src/domains/saves/endec/encoder/byte_encoder.rs
  src/domains/saves/endec/mod.rs
  src/presentation/clients/controllers/acceptor.rs
  src/presentation/clients/request.rs
  src/presentation/cluster_in/outbound/stream.rs
Labels: enhancement

#340 feat: update hwm from leader side
  src/domains/append_only_files/log.rs
  src/domains/cluster_actors/actor.rs
  src/services/handlers/cluster.rs
Labels: feat

#333 feat: sync from dump to wal
  Makefile
  diagrams/raft(5) - commit based on hwm.mmd
  src/adapters/wal/local_wal.rs
  src/adapters/wal/memory_wal.rs
  src/domains/append_only_files/interfaces.rs
  src/domains/append_only_files/logger.rs
  src/domains/cluster_actors/actor.rs
  src/domains/cluster_actors/commands.rs
  src/domains/query_parsers/parsing_context.rs
  src/domains/query_parsers/query_io.rs
  src/lib.rs
  src/presentation/clients/controllers/handler.rs
  src/presentation/cluster_in/communication_manager.rs
  src/presentation/cluster_in/connection_manager.rs
  src/presentation/cluster_in/inbound/stream.rs
  src/presentation/listeners/leader.rs
  src/services/handlers/cluster.rs
  tests/test_recv_full_sync.rs
Labels: refactoring, feat

#342 chore: rename hwm watermark
  src/adapters/wal/local_wal.rs
  src/adapters/wal/memory_wal.rs
  src/domains/append_only_files/interfaces.rs
  src/domains/append_only_files/logger.rs
  src/domains/cluster_actors/actor.rs
  src/domains/peers/kind.rs
  src/domains/query_parsers/parsing_context.rs
  src/domains/query_parsers/query_io.rs
  src/presentation/clients/controllers/handler.rs
  src/presentation/cluster_in/inbound/stream.rs
  src/presentation/listeners/leader.rs
  tests/test_recv_full_sync.rs
Labels: enhancement

#343 feat: add bincode to simplify conversion
  Cargo.lock
  Cargo.toml
  src/adapters/wal/local_wal.rs
  src/domains/append_only_files/log.rs
  src/domains/cluster_actors/replication.rs
  src/domains/peers/identifier.rs
  src/domains/query_parsers/query_io.rs
  src/presentation/listeners/leader.rs
Labels: enhancement, refactoring, feat

#344 refactor : from Bytes to String
  src/domains/append_only_files/log.rs
  src/domains/query_parsers/query_io.rs
  src/presentation/cluster_in/inbound/request.rs
  src/presentation/cluster_in/inbound/stream.rs
  src/presentation/listeners/leader.rs
Labels: refactoring

#345 optimization: no allocation
  src/domains/query_parsers/query_io.rs
Labels: refactoring, feat

#346 chore: add github actions for formatting
  .github/workflows/rustfmt.yaml
Labels: chore

#347 feat: gossip cluster nodes
  src/domains/cluster_actors/actor.rs
  src/domains/cluster_actors/mod.rs
  src/domains/cluster_actors/replication.rs
  src/domains/peers/kind.rs
  src/domains/peers/mod.rs
  src/domains/peers/peer.rs
  src/domains/query_parsers/query_io.rs
  src/presentation/cluster_in/inbound/stream.rs
  src/presentation/cluster_in/outbound/stream.rs
Labels: refactoring, feat

#349 dep: bincode upgrade
  Cargo.lock
  Cargo.toml
Labels: chore

#351 feat: read on follower
  diagrams/raft(6) - discard based on hwm.mmd
  src/domains/append_only_files/logger.rs
  src/domains/cluster_actors/actor.rs
  src/domains/cluster_actors/commands.rs
  src/domains/cluster_actors/consensus.rs
  src/domains/cluster_actors/replication.rs
  src/lib.rs
  src/presentation/clients/controllers/acceptor.rs
  src/presentation/clients/controllers/handler.rs
  src/presentation/clients/controllers/mod.rs
  src/services/handlers/cluster.rs
Labels: refactoring, feat

#358 feat: remove peer triggers cascade
  src/domains/cluster_actors/actor.rs
  src/domains/peers/peer.rs
  src/services/handlers/cluster.rs
Labels: refactoring

#359 feat: leader election
  src/domains/append_only_files/logger.rs
  src/domains/cluster_actors/actor.rs
  src/domains/cluster_actors/commands.rs
  src/domains/cluster_actors/consensus.rs
  src/domains/cluster_actors/consensus/mod.rs
  src/domains/cluster_actors/mod.rs
  src/domains/cluster_actors/replication.rs
  src/domains/cluster_listeners/mod.rs
  src/domains/peers/identifier.rs
  src/domains/peers/peer.rs
  src/domains/query_parsers/query_io.rs
  src/init.rs
  src/lib.rs
  src/presentation/cluster_in/inbound/stream.rs
  src/presentation/listeners/follower.rs
  src/presentation/listeners/leader.rs
  src/services/handlers/cluster.rs
  tests/test_leader_election.rs
Labels: testability, refactoring, feat

#363 feat: early termination of election when vote result is determined
  src/domains/cluster_actors/actor.rs
  src/domains/cluster_actors/commands.rs
  src/domains/cluster_actors/consensus/enums.rs
  src/domains/cluster_actors/consensus/mod.rs
  src/domains/cluster_actors/replication.rs
  src/domains/cluster_listeners/mod.rs
  src/domains/query_parsers/query_io.rs
Labels: refactoring, feat

#366 chore: term increase on election start
  src/domains/cluster_actors/actor.rs
  src/domains/cluster_actors/consensus/mod.rs
  src/domains/cluster_actors/replication/heartbeat.rs
  src/domains/cluster_actors/replication/mod.rs
  src/domains/cluster_listeners/mod.rs
  src/domains/query_parsers/query_io.rs
  src/presentation/listeners/leader.rs
Labels: enhancement

#368 feat: follower increases term
  src/domains/cluster_actors/actor.rs
Labels: feat

#370 chore: nextest config added
  .config/nextest.toml
  src/presentation/cluster_in/outbound/stream.rs
Labels: chore

#371 feat: leader election
  src/domains/cluster_actors/actor.rs
  src/domains/cluster_actors/commands.rs
  src/domains/cluster_actors/consensus/mod.rs
  src/domains/cluster_actors/consensus/voting.rs
  src/domains/cluster_actors/election_state.rs
  src/domains/cluster_actors/heartbeats/heartbeat.rs
  src/domains/cluster_actors/heartbeats/mod.rs
  src/domains/cluster_actors/heartbeats/scheduler.rs
  src/domains/cluster_actors/mod.rs
  src/domains/cluster_actors/replication.rs
  src/domains/cluster_listeners/interfaces.rs
  src/domains/cluster_listeners/mod.rs
  src/domains/mod.rs
  src/domains/peers/connected_types.rs
  src/domains/peers/peer.rs
  src/lib.rs
  src/presentation/clients/controllers/handler.rs
  src/presentation/cluster_in/communication_manager.rs
  src/presentation/cluster_in/inbound/stream.rs
  src/presentation/cluster_in/mod.rs
  src/presentation/cluster_in/outbound/stream.rs
  src/presentation/listeners/follower.rs
  src/presentation/listeners/leader.rs
  src/presentation/listeners/mod.rs
  src/presentation/listeners/non_data_peer.rs
  src/presentation/listeners/peer_listener.rs
  src/services/handlers/cluster.rs
Labels: testability, refactoring, feat

#373 feat: cluster heartbeat / AppendEntry RPC separation
  src/domains/cluster_actors/actor.rs
  src/domains/cluster_actors/commands.rs
  src/domains/cluster_actors/heartbeats/heartbeat.rs
  src/domains/cluster_actors/heartbeats/scheduler.rs
  src/domains/query_parsers/query_io.rs
  src/presentation/listeners/mod.rs
  src/presentation/listeners/peer_listener.rs
  src/services/handlers/cluster.rs
Labels: feat

#375 feat: replication leader agnostic
  src/domains/cluster_actors/actor.rs
  src/services/handlers/cluster.rs
Labels: feat

#376 refactor: cluster listener flattened
  src/actor_registry.rs
  src/domains/cluster_actors/actor.rs
  src/domains/query_parsers/query_io.rs
  src/lib.rs
  src/presentation/clients/controllers/mod.rs
  src/presentation/clusters/communication_manager.rs
  src/presentation/clusters/connection_manager.rs
  src/presentation/clusters/inbound/mod.rs
  src/presentation/clusters/inbound/request.rs
  src/presentation/clusters/inbound/stream.rs
  src/presentation/clusters/listeners/listener.rs
  src/presentation/clusters/listeners/mod.rs
  src/presentation/clusters/listeners/peer_input.rs
  src/presentation/clusters/mod.rs
  src/presentation/clusters/outbound/mod.rs
  src/presentation/clusters/outbound/response.rs
  src/presentation/clusters/outbound/stream.rs
  src/presentation/listeners/mod.rs
  src/presentation/mod.rs
Labels: refactoring

#377 refactor: post leader election feature
  src/domains/caches/actor.rs
  src/domains/caches/cache_manager.rs
  src/domains/caches/cache_objects.rs
  src/domains/cluster_actors/actor.rs
  src/domains/cluster_actors/commands.rs
  src/domains/cluster_actors/consensus/enums.rs
  src/domains/cluster_actors/consensus/mod.rs
  src/domains/cluster_actors/consensus/voting.rs
  src/domains/cluster_actors/election_state.rs
  src/domains/cluster_actors/heartbeats/heartbeat.rs
  src/domains/cluster_actors/heartbeats/scheduler.rs
  src/domains/cluster_actors/replication.rs
  src/domains/config_actors/actor.rs
  src/domains/config_actors/command.rs
  src/domains/config_actors/config_manager.rs
  src/domains/peers/connected_types.rs
  src/domains/peers/identifier.rs
  src/domains/query_parsers/mod.rs
  src/domains/query_parsers/parsing_context.rs
  src/domains/query_parsers/query_io.rs
  src/domains/saves/endec/encoder/byte_encoder.rs
  src/services/handlers/cluster.rs
Labels: bug, refactoring

#379 feat: repl id
  Cargo.lock
  Cargo.toml
  src/domains/caches/cache_manager.rs
  src/domains/cluster_actors/actor.rs
  src/domains/cluster_actors/commands.rs
  src/domains/cluster_actors/heartbeats/heartbeat.rs
  src/domains/cluster_actors/replication.rs
  src/domains/peers/connected_peer_info.rs
  src/domains/peers/peer.rs
  src/domains/query_parsers/query_io.rs
  src/domains/saves/actor.rs
  src/domains/saves/endec/decoder/byte_decoder.rs
  src/domains/saves/endec/decoder/states.rs
  src/domains/saves/endec/encoder/byte_encoder.rs
  src/domains/saves/snapshot/snapshot.rs
  src/lib.rs
  src/presentation/clients/controllers/handler.rs
  src/presentation/clusters/connection_manager.rs
  src/presentation/clusters/inbound/request.rs
  src/presentation/clusters/inbound/stream.rs
  src/presentation/clusters/listeners/listener.rs
  src/presentation/clusters/outbound/stream.rs
  src/services/handlers/cluster.rs
  tests/common.rs
  tests/test_recv_full_sync.rs
Labels: enhancement, testability, refactoring, feat

#382 refactor: lowest follower index -> low watermark, followers -> replicas
  src/domains/append_only_files/logger.rs
  src/domains/cluster_actors/actor.rs
  src/domains/peers/peer.rs
  src/presentation/clusters/inbound/stream.rs
Labels: refactoring

#384 feat: prev_log_index and term taken into consideration on replication
  src/adapters/wal/local_wal.rs
  src/adapters/wal/memory_wal.rs
  src/domains/append_only_files/interfaces.rs
  src/domains/append_only_files/log.rs
  src/domains/append_only_files/logger.rs
  src/domains/cluster_actors/actor.rs
  src/domains/cluster_actors/commands.rs
  src/domains/cluster_actors/consensus/mod.rs
  src/domains/cluster_actors/consensus/voting.rs
  src/domains/cluster_actors/heartbeats/heartbeat.rs
  src/domains/cluster_actors/replication.rs
  src/domains/query_parsers/query_io.rs
  src/presentation/clients/controllers/handler.rs
  src/presentation/clusters/listeners/peer_input.rs
  src/services/handlers/cluster.rs
Labels: enhancement, refactoring, feat

#385 feat: Append entries RPC ravamped
  src/adapters/wal/local_wal.rs
  src/adapters/wal/memory_wal.rs
  src/domains/append_only_files/interfaces.rs
  src/domains/append_only_files/logger.rs
  src/domains/cluster_actors/actor.rs
  src/services/handlers/cluster.rs
Labels: enhancement, testability, refactoring

#386 rm: remove log index type
  src/domains/append_only_files/log.rs
  src/domains/caches/cache_manager.rs
  src/domains/cluster_actors/actor.rs
  src/domains/cluster_actors/consensus/voting.rs
  src/domains/cluster_actors/heartbeats/heartbeat.rs
  src/domains/cluster_actors/replication.rs
  src/domains/query_parsers/query_io.rs
  src/presentation/clients/controllers/mod.rs
  src/presentation/clusters/listeners/mod.rs
  src/presentation/clusters/outbound/stream.rs
Labels: feat

#388 feat: read index
  src/domains/caches/actor.rs
  src/domains/caches/cache_manager.rs
  src/domains/caches/command.rs
  src/domains/caches/mod.rs
  src/domains/caches/read_queue.rs
  src/domains/cluster_actors/actor.rs
  src/domains/cluster_actors/replication.rs
  src/lib.rs
  src/presentation/clients/controllers/handler.rs
  src/presentation/clients/request.rs
  src/presentation/clients/stream.rs
  src/presentation/clusters/inbound/stream.rs
  src/presentation/clusters/outbound/stream.rs
  src/services/handlers/cache.rs
  src/services/handlers/cluster.rs
  tests/test_keys.rs
  tests/test_save_read_snapshot.rs
  tests/test_set_get.rs
Labels: testability, refactoring, feat

#389 refactor: post 353
  src/domains/caches/cache_manager.rs
  src/domains/caches/cache_objects.rs
  src/domains/caches/command.rs
  src/domains/caches/read_queue.rs
  src/domains/cluster_actors/actor.rs
  src/domains/cluster_actors/consensus/voting.rs
  src/domains/query_parsers/query_io.rs
  src/domains/saves/snapshot/snapshot.rs
  src/services/handlers/cache.rs
Labels: refactoring

#390 feat: cluster nodes operation
  src/domains/cluster_actors/actor.rs
  src/domains/cluster_actors/replication.rs
  src/services/handlers/cluster.rs
  tests/common.rs
Labels: testability, refactoring, feat

#392 feat: reject consensus - leader step down on consensus rejection
  src/domains/cluster_actors/actor.rs
  src/domains/cluster_actors/commands.rs
  src/domains/cluster_actors/commands/election.rs
  src/domains/cluster_actors/commands/mod.rs
  src/domains/cluster_actors/commands/types.rs
  src/domains/cluster_actors/commands/write_con.rs
  src/domains/cluster_actors/consensus/mod.rs
  src/domains/cluster_actors/consensus/voting.rs
  src/domains/cluster_actors/election_state.rs
  src/domains/cluster_actors/heartbeats/heartbeat.rs
  src/domains/cluster_actors/heartbeats/scheduler.rs
  src/domains/cluster_actors/replication.rs
  src/domains/peers/peer.rs
  src/domains/query_parsers/query_io.rs
  src/domains/saves/actor.rs
  src/presentation/clients/controllers/handler.rs
  src/presentation/clusters/inbound/stream.rs
  src/presentation/clusters/listeners/listener.rs
  src/presentation/clusters/listeners/peer_input.rs
  src/services/handlers/cluster.rs
  tests/test_save_read_snapshot.rs
Labels: enhancement, refactoring, feat

#395 feat: decrease match index on log inconsistency detection
  src/domains/cluster_actors/actor.rs
  src/domains/cluster_actors/commands/write_con.rs
  src/domains/cluster_actors/mod.rs
  src/domains/peers/peer.rs
  src/domains/query_parsers/query_io.rs
  src/presentation/clusters/inbound/stream.rs
  src/presentation/clusters/listeners/mod.rs
  src/presentation/clusters/outbound/stream.rs
  src/services/handlers/cluster.rs
Labels: enhancement, feat

#396 feat: paramerize topology path
  src/domains/cluster_actors/actor.rs
  src/init.rs
  src/lib.rs
  src/services/handlers/cluster.rs
  tests/common.rs
Labels: testability, feat

#397 feat: voter votes only once
  src/domains/cluster_actors/actor.rs
  src/domains/cluster_actors/commands/write_con.rs
  src/domains/cluster_actors/consensus/mod.rs
  src/domains/cluster_actors/consensus/voting.rs
Labels: testability, feat

#398 refactor: consensus vote counting
  src/domains/cluster_actors/actor.rs
  src/domains/cluster_actors/consensus/mod.rs
  src/domains/cluster_actors/consensus/voting.rs
Labels: refactoring

#399 fix: election voting count logic
  src/domains/cluster_actors/actor.rs
  src/domains/cluster_actors/consensus/election.rs
  src/domains/cluster_actors/consensus/log.rs
  src/domains/cluster_actors/consensus/mod.rs
  src/domains/cluster_actors/consensus/voting.rs
  src/domains/cluster_actors/mod.rs
  src/domains/cluster_actors/replication.rs
Labels: bug, testability, refactoring

#400 dep: tokio, tempfile versionup
  Cargo.lock
  Cargo.toml
Labels: chore

#404 fix: test_full_sync_on_newly_added_replica
  src/presentation/clusters/inbound/stream.rs
  tests/test_sync.rs
Labels: bug, testability

#410 doc: read your own write
  README.md
  diagrams/follower_reads.mmd
Labels: documentation

#413 feat: client sessions integration & tests
  src/domains/append_only_files/log.rs
  src/domains/append_only_files/mod.rs
  src/domains/cluster_actors/actor.rs
  src/domains/cluster_actors/commands/election.rs
  src/domains/cluster_actors/commands/mod.rs
  src/domains/cluster_actors/commands/write_con.rs
  src/domains/cluster_actors/consensus/log.rs
  src/domains/cluster_actors/heartbeats/heartbeat.rs
  src/domains/cluster_actors/mod.rs
  src/domains/cluster_actors/replication.rs
  src/domains/cluster_actors/session.rs
  src/domains/peers/identifier.rs
  src/presentation/clients/controllers/acceptor.rs
  src/presentation/clients/controllers/handler.rs
  src/presentation/clients/mod.rs
  src/presentation/clients/request.rs
  src/presentation/clients/session.rs
  src/presentation/clients/stream.rs
  src/presentation/clusters/communication_manager.rs
  src/presentation/clusters/connection_manager.rs
  src/services/handlers/cluster.rs
Labels: enhancement, testability, feat

#415 refactor: duva cli structure
  duva-cli/src/cli.rs
  duva-cli/src/command.rs
  duva-cli/src/controller.rs
  duva-cli/src/main.rs
Labels: refactoring

#417 feat: save latest index
  duva-cli/src/command.rs
  duva-cli/src/controller.rs
  duva-cli/src/main.rs
  duva/src/domains/cluster_actors/session.rs
  duva/src/presentation/clients/mod.rs
  duva/src/presentation/clients/parser.rs
  duva/src/presentation/clients/request.rs
  duva/src/presentation/clients/stream.rs
Labels: enhancement, refactoring, feat

#418 refactor: apply clippy
  duva-cli/src/command.rs
  duva-cli/src/controller.rs
  duva-cli/src/main.rs
  duva/src/adapters/io/tokio_stream.rs
  duva/src/adapters/wal/local_wal.rs
  duva/src/clients/utils.rs
  duva/src/domains/append_only_files/logger.rs
  duva/src/domains/caches/actor.rs
  duva/src/domains/caches/cache_manager.rs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/consensus/election.rs
  duva/src/domains/cluster_actors/heartbeats/heartbeat.rs
  duva/src/domains/peers/peer.rs
  duva/src/domains/query_parsers/query_io.rs
  duva/src/domains/saves/actor.rs
  duva/src/domains/saves/endec/decoder/byte_decoder.rs
  duva/src/domains/saves/endec/decoder/states.rs
  duva/src/domains/saves/endec/encoder/byte_encoder.rs
  duva/src/domains/saves/snapshot/mod.rs
  duva/src/domains/saves/snapshot/snapshot.rs
  duva/src/domains/saves/snapshot/snapshot_loader.rs
  duva/src/presentation/clients/controllers/acceptor.rs
  duva/src/presentation/clients/controllers/handler.rs
  duva/src/presentation/clients/stream.rs
  duva/src/presentation/clusters/connection_manager.rs
  duva/src/presentation/clusters/inbound/stream.rs
  duva/src/presentation/clusters/listeners/listener.rs
  duva/src/presentation/clusters/outbound/stream.rs
  duva/src/services/handlers/cluster.rs
  duva/src/services/interface.rs
Labels: refactoring

#419 refactor: remove ambiguity in naming
  duva.tp
  duva/src/domains/append_only_files/logger.rs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/replication.rs
  duva/src/services/handlers/cluster.rs
Labels: enhancement, refactoring
