Repository Migorithm/duva, pull requests merged in 2025-04, with the labels that each got.

#422 feat: cli history
  Cargo.lock
  duva-cli.hist
  duva-cli/Cargo.toml
  duva-cli/src/controller.rs
  duva-cli/src/editor.rs
  duva-cli/src/main.rs
Labels: enhancement, feat

#423 fix: info not retrieving bug
  .gitignore
  duva-cli.hist
  duva-cli/src/command.rs
  duva-cli/src/controller.rs
  duva-cli/src/editor.rs
  duva/src/presentation/clients/stream.rs
Labels: bug

#425 fix: use of client id stored on stream
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/replication.rs
  duva/src/presentation/clients/stream.rs
Labels: bug

#429 fix: reelection error
  duva/src/domains/cluster_actors/actor.rs
  duva/src/services/handlers/cluster.rs
  duva/tests/test_cluster_forget_makes_all_nodes_forget_target_node.rs
  duva/tests/test_cluster_forget_when_wrong_id_given.rs
  duva/tests/test_cluster_known_nodes_increase_when_new_replica_is_added.rs
  duva/tests/test_leader_election.rs
  duva/tests/test_removes_node_when_heartbeat_is_not_received_for_certain_time.rs
Labels: bug

#430 fix: error point catch
  duva/src/domains/append_only_files/logger.rs
  duva/src/domains/cluster_actors/actor.rs
Labels: bug

#431 test: set twice after election
  duva/tests/test_leader_election.rs
Labels: testability

#432 feat: delete operation
  duva-cli/src/command.rs
  duva-cli/src/controller.rs
  duva/src/adapters/wal/local_wal.rs
  duva/src/domains/append_only_files/log.rs
  duva/src/domains/caches/actor.rs
  duva/src/domains/caches/cache_manager.rs
  duva/src/domains/caches/command.rs
  duva/src/domains/saves/endec/mod.rs
  duva/src/presentation/clients/controllers/handler.rs
  duva/src/presentation/clients/parser.rs
  duva/src/presentation/clients/request.rs
  duva/src/services/handlers/cache.rs
  duva/tests/test_del.rs
Labels: feat

#436 refactor: allow for multi binary
  Cargo.lock
  Cargo.toml
  duva-cli/src/error.rs
  duva-client/Cargo.toml
  duva-client/src/cli/cli.rs
  duva-client/src/cli/editor.rs
  duva-client/src/cli/main.rs
  duva-client/src/command.rs
  duva-client/src/controller.rs
  duva-client/src/lib.rs
Labels: refactoring, chore

#437 doc: display demo for cli
  README.md
Labels: documentation

#444 feat: pull-based reconnection to new leader instance
  duva-client/src/cli/main.rs
  duva-client/src/command.rs
  duva-client/src/controller.rs
  duva/src/clients/authentications.rs
  duva/src/clients/utils.rs
  duva/src/domains/peers/identifier.rs
  duva/src/domains/peers/mod.rs
  duva/src/lib.rs
  duva/src/presentation/clients/stream.rs
Labels: bug, feat

#447 doc: pull based reconnection
  .gitignore
  README.md
Labels: documentation

#448 doc: diagram on reconnection on leader failure
  README.md
  diagrams/reconnection-on-leader-failure.mmd
Labels: documentation

#411 feat: implement lazy discovery leader
  Makefile
  duva-client/src/command.rs
  duva-client/src/controller.rs
  duva/src/domains/caches/cache_manager.rs
  duva/src/domains/caches/command.rs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/commands/mod.rs
  duva/src/domains/cluster_actors/commands/types.rs
  duva/src/domains/cluster_actors/replication.rs
  duva/src/domains/query_parsers/query_io.rs
  duva/src/lib.rs
  duva/src/presentation/clients/controllers/handler.rs
  duva/src/presentation/clients/parser.rs
  duva/src/presentation/clients/request.rs
  duva/src/presentation/clusters/communication_manager.rs
  duva/src/presentation/clusters/connection_manager.rs
  duva/src/presentation/clusters/inbound/stream.rs
  duva/src/presentation/clusters/listeners/listener.rs
  duva/src/presentation/clusters/listeners/mod.rs
  duva/src/presentation/clusters/outbound/stream.rs
  duva/src/services/handlers/cache.rs
  duva/src/services/handlers/cluster.rs
  duva/tests/cluster_ops/mod.rs
  duva/tests/cluster_ops/test_disseminate_peers.rs
  duva/tests/cluster_ops/test_lazy_discovery.rs
  duva/tests/common.rs
  run.sh
Labels: bug, feat

#449 refactor: improve testability
  duva/tests/replication_ops/test_leader_election.rs
Labels: enhancement, testability, refactoring

#451 fix: electiont test
  duva/src/domains/cluster_actors/heartbeats/scheduler.rs
  duva/tests/common.rs
  duva/tests/replication_ops/test_leader_election.rs
Labels: bug, testability

#452 feat: role command
  duva-client/src/command.rs
  duva-client/src/controller.rs
  duva/src/domains/cluster_actors/commands/mod.rs
  duva/src/domains/cluster_actors/replication.rs
  duva/src/presentation/clients/controllers/handler.rs
  duva/src/presentation/clients/parser.rs
  duva/src/presentation/clients/request.rs
  duva/src/presentation/clusters/communication_manager.rs
  duva/src/presentation/clusters/connection_manager.rs
  duva/src/services/handlers/cluster.rs
Labels: feat

#453 rm: dicover peers
  duva/src/domains/cluster_actors/replication.rs
  duva/src/init.rs
  duva/src/lib.rs
  duva/src/main.rs
Labels: refactoring, chore

#454 feat: topology change subscription
  Makefile
  duva-client/src/broker.rs
  duva-client/src/cli/main.rs
  duva-client/src/cli/output_render.rs
  duva-client/src/cli_input.rs
  duva-client/src/command.rs
  duva-client/src/controller.rs
  duva-client/src/lib.rs
  duva/src/domains/append_only_files/logger.rs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/commands/mod.rs
  duva/src/domains/error.rs
  duva/src/domains/query_parsers/query_io.rs
  duva/src/lib.rs
  duva/src/presentation/clients/authenticate.rs
  duva/src/presentation/clients/controller.rs
  duva/src/presentation/clients/controllers/acceptor.rs
  duva/src/presentation/clients/controllers/mod.rs
  duva/src/presentation/clients/mod.rs
  duva/src/presentation/clients/stream.rs
  duva/src/presentation/clusters/communication_manager.rs
  duva/src/presentation/clusters/outbound/stream.rs
  duva/src/services/handlers/cluster.rs
Labels: feat

#456 doc: topology-change
  README.md
  diagrams/topology-change-subscription.mmd
Labels: documentation

#457 doc: subscription -> notification
  README.md
Labels: documentation

#458 testability : Use of client cli directly
  duva-client/src/broker.rs
  duva-client/src/cli_input.rs
  duva-client/src/command.rs
  duva/src/clients/mod.rs
  duva/src/clients/utils.rs
  duva/src/presentation/clients/controller.rs
  duva/tests/client_ops/mod.rs
  duva/tests/client_ops/test_config_get_dir.rs
  duva/tests/client_ops/test_del.rs
  duva/tests/client_ops/test_exists.rs
  duva/tests/client_ops/test_idempotent_client.rs
  duva/tests/client_ops/test_keys.rs
  duva/tests/client_ops/test_replication_info.rs
  duva/tests/client_ops/test_set_get.rs
  duva/tests/client_ops/test_snapshot_persists_and_recovers_state.rs
  duva/tests/cluster_ops/test_cluster_forget_makes_all_nodes_forget_target_node.rs
  duva/tests/cluster_ops/test_cluster_forget_when_wrong_id_given.rs
  duva/tests/cluster_ops/test_cluster_known_nodes_increase_when_new_replica_is_added.rs
  duva/tests/cluster_ops/test_lazy_discovery.rs
  duva/tests/cluster_ops/test_removes_node_when_heartbeat_is_not_received_for_certain_time.rs
  duva/tests/common.rs
  duva/tests/replication_ops/test_leader_election.rs
  duva/tests/replication_ops/test_raft_happy_case.rs
  duva/tests/replication_ops/test_sync.rs
Labels: testability, refactoring

#459 refactor: cli
  Makefile
  duva-client/Cargo.toml
  duva-client/src/broker/input_queue.rs
  duva-client/src/broker/mod.rs
  duva-client/src/broker/read_stream.rs
  duva-client/src/broker/write_stream.rs
  duva-client/src/cli/main.rs
  duva-client/src/cli/output_render.rs
  duva-client/src/cli_input.rs
  duva-client/src/command.rs
  duva-client/src/controller.rs
  duva-client/src/lib.rs
  duva/src/domains/caches/cache_objects.rs
  duva/src/domains/saves/endec/decoder/byte_decoder.rs
  duva/src/presentation/clusters/communication_manager.rs
  duva/src/presentation/clusters/listeners/mod.rs
  duva/tests/common.rs
Labels: enhancement

#460 chore: cleanup
  duva/src/adapters/wal/local_wal.rs
  duva/src/domains/append_only_files/log.rs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/peers/peer.rs
Labels: chore

#463 feat: cli - auto completion & Clear the Terminal & Display ASCII Art
  .vscode/settings.json
  Cargo.lock
  Makefile
  duva-client/Cargo.toml
  duva-client/src/cli/editor/completion.rs
  duva-client/src/cli/editor/hints.rs
  duva-client/src/cli/editor/mod.rs
  duva-client/src/cli/main.rs
  duva-client/src/controller.rs
  duva/src/domains/cluster_actors/actor.rs
Labels: feat

#464 doc: autocompletion
  README.md
Labels: documentation

#466 chore: license
  LICENSE
  README.md
  duva-client/src/cli/main.rs
Labels: documentation, chore

#469 feat: INCR
  duva-client/src/broker/mod.rs
  duva-client/src/cli/editor/completion.rs
  duva-client/src/cli/editor/hints.rs
  duva-client/src/cli/main.rs
  duva-client/src/command.rs
  duva-client/src/controller.rs
  duva/src/clients/mod.rs
  duva/src/domains/caches/actor.rs
  duva/src/domains/caches/cache_manager.rs
  duva/src/domains/caches/cache_objects.rs
  duva/src/domains/caches/command.rs
  duva/src/domains/caches/read_queue.rs
  duva/src/domains/query_parsers/query_io.rs
  duva/src/presentation/clients/controller.rs
  duva/src/presentation/clients/parser.rs
  duva/src/presentation/clients/request.rs
  duva/src/presentation/clients/stream.rs
  duva/src/services/handlers/cache.rs
  duva/tests/client_ops/mod.rs
  duva/tests/client_ops/test_incr.rs
  duva/tests/common.rs
Labels: bug, testability, refactoring, feat

#472 docs: commnads
  docs/_commands/echo.md
  docs/_commands/ping.md
  docs/_commands/replicaof.md
Labels: documentation

#476 feat: DECR
  duva-client/src/cli/editor/completion.rs
  duva-client/src/cli/editor/hints.rs
  duva-client/src/command.rs
  duva-client/src/controller.rs
  duva-client/src/lib.rs
  duva/src/domains/error.rs
  duva/src/presentation/clients/controller.rs
  duva/src/presentation/clients/parser.rs
  duva/src/presentation/clients/request.rs
  duva/tests/client_ops/mod.rs
  duva/tests/client_ops/test_decr.rs
Labels: feat

#477 docs: decr
  README.md
  docs/_commands/decr.md
Labels: documentation

#478 refactor : unifying client action
  duva-client/src/broker/mod.rs
  duva-client/src/cli/main.rs
  duva-client/src/command.rs
  duva-client/src/controller.rs
  duva/src/presentation/clients/parser.rs
  duva/src/presentation/clients/request.rs
  duva/src/presentation/clients/stream.rs
  duva/src/services/handlers/cache.rs
Labels: refactoring

#479 chore: issue template
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: chore

#480 feat: reconnection on reboot
  Cargo.lock
  Makefile
  duva-client/src/broker/mod.rs
  duva-client/src/controller.rs
  duva/Cargo.toml
  duva/src/adapters/wal/local_wal.rs
  duva/src/domains/caches/cache_manager.rs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/commands/mod.rs
  duva/src/domains/cluster_actors/consensus/election.rs
  duva/src/domains/cluster_actors/heartbeats/heartbeat.rs
  duva/src/domains/cluster_actors/replication.rs
  duva/src/domains/peers/cluster_peer.rs
  duva/src/domains/peers/mod.rs
  duva/src/domains/query_parsers/query_io.rs
  duva/src/init.rs
  duva/src/lib.rs
  duva/src/macros.rs
  duva/src/main.rs
  duva/src/presentation/clients/controller.rs
  duva/src/presentation/clients/request.rs
  duva/src/presentation/clusters/communication_manager.rs
  duva/src/presentation/clusters/inbound/stream.rs
  duva/src/presentation/clusters/listeners/listener.rs
  duva/src/presentation/clusters/outbound/stream.rs
  duva/tests/client_ops/test_snapshot_persists_and_recovers_state.rs
  duva/tests/cluster_ops/mod.rs
  duva/tests/cluster_ops/test_cluster_forget_makes_all_nodes_forget_target_node.rs
  duva/tests/cluster_ops/test_cluster_forget_when_wrong_id_given.rs
  duva/tests/cluster_ops/test_heartbeat.rs
  duva/tests/cluster_ops/test_lazy_discovery.rs
  duva/tests/cluster_ops/test_reconnection_on_reboot.rs
  duva/tests/cluster_ops/test_removes_node_when_heartbeat_is_not_received_for_certain_time.rs
  duva/tests/replication_ops/test_leader_election.rs
  duva/tests/replication_ops/test_raft_happy_case.rs
  duva/tests/replication_ops/test_sync.rs
Labels: feat

#482 docs: post on reconnection on reboot
  docs/_posts/2025-04-22-reconnection-on-reboot.md
Labels: documentation

#485 test: simplify cluster nodes test
  duva/src/domains/cluster_actors/actor.rs
Labels: testability

#487 feat: topology_file_handler
  duva/src/domains/cluster_actors/actor.rs
  duva/src/init.rs
  duva/src/lib.rs
  duva/src/main.rs
  duva/src/services/handlers/cluster.rs
Labels: refactoring, feat

#489 optimize: discover_cluster into domain
  duva/src/actor_registry.rs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/commands/mod.rs
  duva/src/lib.rs
  duva/src/presentation/clients/controller.rs
  duva/src/presentation/clusters/communication_manager.rs
  duva/src/presentation/clusters/connection_manager.rs
  duva/src/presentation/clusters/inbound/stream.rs
  duva/src/presentation/clusters/mod.rs
  duva/src/presentation/clusters/outbound/stream.rs
  duva/src/services/handlers/cluster.rs
Labels: enhancement, refactoring, kill legacy

#490 refactor: in/outbound stream logic into domain
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/commands/cluster_actor_command.rs
  duva/src/domains/cluster_actors/commands/mod.rs
  duva/src/domains/cluster_actors/commands/peer_listener_command.rs
  duva/src/domains/cluster_actors/listener.rs
  duva/src/domains/cluster_actors/mod.rs
  duva/src/domains/cluster_actors/peer_connections/inbound/mod.rs
  duva/src/domains/cluster_actors/peer_connections/inbound/request.rs
  duva/src/domains/cluster_actors/peer_connections/inbound/stream.rs
  duva/src/domains/cluster_actors/peer_connections/mod.rs
  duva/src/domains/cluster_actors/peer_connections/outbound/mod.rs
  duva/src/domains/cluster_actors/peer_connections/outbound/response.rs
  duva/src/domains/cluster_actors/peer_connections/outbound/stream.rs
  duva/src/domains/peers/connected_peer_info.rs
  duva/src/domains/peers/peer.rs
  duva/src/lib.rs
  duva/src/presentation/clusters/listeners/mod.rs
  duva/src/presentation/clusters/mod.rs
  duva/src/presentation/clusters/outbound/mod.rs
Labels: enhancement, refactoring

#491 feat: ttl
  docs/_commands/ttl.md
  duva-client/src/cli/editor/completion.rs
  duva-client/src/cli/editor/hints.rs
  duva-client/src/controller.rs
  duva/src/domains/caches/actor.rs
  duva/src/domains/caches/cache_manager.rs
  duva/src/domains/caches/cache_objects.rs
  duva/src/domains/caches/command.rs
  duva/src/domains/caches/read_queue.rs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/query_parsers/query_io.rs
  duva/src/domains/saves/endec/decoder/byte_decoder.rs
  duva/src/domains/saves/endec/encoder/byte_encoder.rs
  duva/src/presentation/clients/controller.rs
  duva/src/presentation/clients/request.rs
  duva/src/services/handlers/cache.rs
  duva/tests/client_ops/mod.rs
  duva/tests/client_ops/test_ttl.rs
Labels: testability, refactoring, feat

#492 fix: missing assert
  duva/tests/client_ops/test_ttl.rs
Labels: chore

#493 chore: renaming from WAL -> OpLogs
  duva/src/adapters/mod.rs
  duva/src/adapters/op_logs/disk_based.rs
  duva/src/adapters/op_logs/memory_based.rs
  duva/src/adapters/op_logs/mod.rs
  duva/src/adapters/wal/mod.rs
  duva/src/domains/append_only_files/mod.rs
  duva/src/domains/caches/cache_manager.rs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/commands/cluster_actor_command.rs
  duva/src/domains/cluster_actors/commands/peer_listener_command.rs
  duva/src/domains/cluster_actors/commands/types.rs
  duva/src/domains/cluster_actors/heartbeats/heartbeat.rs
  duva/src/domains/cluster_actors/peer_connections/inbound/stream.rs
  duva/src/domains/mod.rs
  duva/src/domains/operation_logs/interfaces.rs
  duva/src/domains/operation_logs/logger.rs
  duva/src/domains/operation_logs/mod.rs
  duva/src/domains/operation_logs/operation.rs
  duva/src/domains/query_parsers/query_io.rs
  duva/src/lib.rs
  duva/src/main.rs
  duva/src/presentation/clients/request.rs
  duva/src/services/handlers/cluster.rs
Labels: refactoring, chore

#495 enhancement: raft revisited
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/heartbeats/scheduler.rs
  duva/src/domains/cluster_actors/replication.rs
Labels: enhancement, refactoring

#496 fix: flaky test
  duva/src/domains/caches/command.rs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/services/handlers/cluster.rs
  duva/tests/cluster_ops/test_cluster_forget_makes_all_nodes_forget_target_node.rs
Labels: bug, testability

#497 feat: gossip-based reconnection
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/peers/cluster_peer.rs
  duva/src/services/handlers/cluster.rs
Labels: testability, feat

#502 chore: remove stop sentinel
  .github/workflows/build-and-push-image.yaml
  .github/workflows/rustfmt.yaml
  README.md
  duva/src/domains/caches/command.rs
  duva/src/services/handlers/cache.rs
Labels: chore

#506 Using bytes crate efficiently
  duva/src/adapters/op_logs/disk_based.rs
  duva/src/domains/cluster_actors/commands/peer_listener_command.rs
  duva/src/domains/operation_logs/operation.rs
  duva/src/domains/query_parsers/query_io.rs
Labels: enhancement

#504 chore: lib test on ci
  .github/actions/test/action.yaml
  .github/workflows/build-and-push-image.yaml
Labels: chore

#510 feat: disk-based operation logs
  Cargo.lock
  duva/Cargo.toml
  duva/src/adapters/op_logs/disk_based.rs
  duva/src/adapters/op_logs/memory_based.rs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/peer_connections/inbound/stream.rs
  duva/src/domains/operation_logs/interfaces.rs
  duva/src/domains/operation_logs/logger.rs
  duva/src/main.rs
  duva/src/services/handlers/cluster.rs
Labels: enhancement, testability, feat

#512 chore: add compilation checker
  .github/workflows/rustfmt.yaml
Labels: chore

#513 refactor: peer state as struct
  duva/src/adapters/op_logs/disk_based.rs
  duva/src/domains/caches/actor.rs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/mod.rs
  duva/src/domains/cluster_actors/peer_connections/inbound/stream.rs
  duva/src/domains/peers/cluster_peer.rs
  duva/src/domains/peers/connected_peer_info.rs
  duva/src/domains/peers/peer.rs
  duva/src/domains/query_parsers/query_io.rs
Labels: refactoring

#514 doc: consistent hashing
  diagrams/consistent_hashing.mmd
Labels: documentation

#515 refactor: remove ClusterNode
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/commands/cluster_actor_command.rs
  duva/src/domains/cluster_actors/heartbeats/heartbeat.rs
  duva/src/domains/cluster_actors/peer_connections/inbound/stream.rs
  duva/src/domains/cluster_actors/peer_connections/outbound/stream.rs
  duva/src/domains/cluster_actors/replication.rs
  duva/src/domains/peers/cluster_peer.rs
  duva/src/domains/peers/connected_peer_info.rs
  duva/src/domains/peers/identifier.rs
  duva/src/domains/peers/mod.rs
  duva/src/domains/peers/peer.rs
  duva/src/domains/query_parsers/query_io.rs
  duva/src/init.rs
  duva/src/lib.rs
  duva/src/presentation/clusters/communication_manager.rs
Labels: enhancement, refactoring

#516 feat: stuff match index data
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/peers/peer.rs
Labels: enhancement, refactoring

#517 refactor: remove types
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/commands/mod.rs
  duva/src/domains/cluster_actors/commands/types.rs
  duva/src/domains/cluster_actors/peer_connections/inbound/stream.rs
  duva/src/domains/cluster_actors/peer_connections/outbound/stream.rs
  duva/src/domains/peers/peer.rs
  duva/src/domains/query_parsers/query_io.rs
Labels: refactoring

#518 optimization: remove clone
  duva/src/adapters/op_logs/disk_based.rs
Labels: enhancement

#520 refactor: enum->struct for CacheValue
  duva/src/domains/caches/actor.rs
  duva/src/domains/caches/cache_manager.rs
  duva/src/domains/caches/cache_objects.rs
  duva/src/domains/query_parsers/query_io.rs
  duva/src/services/handlers/cache.rs
Labels: enhancement, refactoring

#522 feat: post logging validation on delta changes
  docs/_posts/2025-04-30-deferred_validation.markdown
  duva-client/src/broker/mod.rs
  duva/src/adapters/op_logs/disk_based.rs
  duva/src/adapters/op_logs/memory_based.rs
  duva/src/domains/caches/cache_manager.rs
  duva/src/domains/caches/cache_objects.rs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/operation_logs/operation.rs
  duva/src/domains/peers/peer.rs
  duva/src/domains/query_parsers/query_io.rs
  duva/src/presentation/clients/controller.rs
  duva/src/presentation/clients/request.rs
  duva/src/services/handlers/cluster.rs
Labels: refactoring, feat

#523 chore: remove clients, todos
  duva-client/src/broker/mod.rs
  duva/src/clients/authentications.rs
  duva/src/clients/mod.rs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/peer_connections/inbound/stream.rs
  duva/src/domains/peers/connected_peer_info.rs
  duva/src/lib.rs
  duva/src/presentation/clients/authenticate.rs
  duva/src/presentation/clients/controller.rs
  duva/src/presentation/clients/mod.rs
  duva/src/presentation/clients/stream.rs
  duva/tests/client_ops/test_snapshot_persists_and_recovers_state.rs
  duva/tests/cluster_ops/test_lazy_discovery.rs
Labels: refactoring, chore

#527 Add image to README.md
  README.md
Labels: documentation
