Repository Migorithm/duva, pull requests merged in 2025-07, with the labels that each got.

#701 feat: List type support on server side
  duva-client/src/controller.rs
  duva/src/domains/caches/actor.rs
  duva/src/domains/caches/cache_manager.rs
  duva/src/domains/caches/cache_objects/value.rs
  duva/src/domains/caches/command.rs
  duva/src/domains/caches/read_queue.rs
  duva/src/domains/caches/service.rs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/actor/tests/partitionings.rs
  duva/src/domains/query_io.rs
  duva/src/domains/saves/endec/encoder.rs
  duva/src/presentation/clients/controller.rs
Labels: refactoring, feat

#703 refactor: partial eq, testability
  duva/src/domains/caches/actor.rs
  duva/src/domains/caches/cache_manager.rs
  duva/src/domains/caches/cache_objects/entry.rs
  duva/src/domains/caches/cache_objects/value.rs
  duva/src/domains/cluster_actors/actor/tests/partitionings.rs
  duva/src/domains/cluster_actors/actor/tests/replications.rs
  duva/src/domains/saves/endec/decoder.rs
  duva/src/domains/saves/endec/encoder.rs
Labels: testability, refactoring

#708 docs: typo
  README.md
Labels: documentation

#709 fix: change hash ring update after migration done
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/actor/tests/cluster_managements.rs
Labels: bug

#713 fix: server panic when wrong connection is attempted
  duva/src/config.rs
  duva/src/domains/peers/connections/outbound/stream.rs
  duva/src/domains/peers/identifier.rs
  duva/src/domains/peers/peer.rs
  duva/src/domains/query_io.rs
  duva/src/presentation/clients/controller.rs
  duva/src/presentation/clients/request.rs
  duva/src/presentation/clusters/communication_manager.rs
Labels: bug

#714 fix: hash_ring update logic when cluster meet
  duva/src/domains/cluster_actors/actor.rs
Labels: bug

#715 refactor: make cluster command eq check evaluatable
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/actor/tests/cluster_managements.rs
  duva/src/domains/cluster_actors/actor/tests/elections.rs
  duva/src/domains/cluster_actors/actor/tests/mod.rs
  duva/src/domains/cluster_actors/actor/tests/partitionings.rs
  duva/src/domains/cluster_actors/actor/tests/replications.rs
  duva/src/domains/cluster_actors/command.rs
  duva/src/domains/cluster_actors/consensus/log.rs
  duva/src/domains/cluster_actors/hash_ring/migration_task.rs
  duva/src/domains/cluster_actors/replication.rs
  duva/src/domains/peers/command.rs
  duva/src/domains/peers/connections/connection_types.rs
  duva/src/domains/peers/connections/inbound/stream.rs
  duva/src/domains/peers/connections/outbound/stream.rs
  duva/src/domains/peers/peer.rs
  duva/src/domains/peers/service.rs
  duva/src/lib.rs
  duva/src/presentation/clusters/communication_manager.rs
  duva/src/types.rs
Labels: testability, refactoring

#716 test: check if `migrate_batch` send peer_message
  duva/src/domains/caches/cache_objects/value.rs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/actor/tests/mod.rs
  duva/src/domains/cluster_actors/actor/tests/partitionings.rs
Labels: testability

#720 feat: quick list operation
  Cargo.lock
  duva/Cargo.toml
  duva/src/domains/caches/cache_objects/mod.rs
  duva/src/domains/caches/cache_objects/types/mod.rs
  duva/src/domains/caches/cache_objects/types/quicklist.rs
  duva/src/domains/caches/cache_objects/value.rs
Labels: testability, refactoring, feat

#723 feat: lpop
  duva-client/src/controller.rs
  duva/src/domains/caches/actor.rs
  duva/src/domains/caches/cache_manager.rs
  duva/src/domains/caches/command.rs
  duva/src/domains/caches/lru_cache.rs
  duva/src/domains/caches/service.rs
  duva/src/domains/operation_logs/operation.rs
  duva/src/presentation/clients/controller.rs
  duva/src/presentation/clients/request.rs
  duva/tests/client_ops/mod.rs
  duva/tests/client_ops/test_lpop.rs
Labels: testability, refactoring, feat

#725 feat: RPUSH
  duva-client/src/controller.rs
  duva/src/domains/caches/actor.rs
  duva/src/domains/caches/cache_manager.rs
  duva/src/domains/caches/command.rs
  duva/src/domains/caches/service.rs
  duva/src/domains/operation_logs/operation.rs
  duva/src/presentation/clients/controller.rs
  duva/src/presentation/clients/request.rs
  duva/tests/client_ops/mod.rs
  duva/tests/client_ops/test_rpush.rs
  duva/tests/common.rs
Labels: testability, feat

#732 feat: llen
  duva-client/src/controller.rs
  duva/src/domains/caches/actor.rs
  duva/src/domains/caches/cache_manager.rs
  duva/src/domains/caches/command.rs
  duva/src/domains/caches/service.rs
  duva/src/presentation/clients/controller.rs
  duva/src/presentation/clients/request.rs
  duva/tests/client_ops/mod.rs
  duva/tests/client_ops/test_llen.rs
Labels: testability, feat

#734 feat LRange
  duva-client/src/controller.rs
  duva/src/domains/caches/actor.rs
  duva/src/domains/caches/cache_manager.rs
  duva/src/domains/caches/command.rs
  duva/src/domains/caches/lru_cache.rs
  duva/src/domains/caches/service.rs
  duva/src/presentation/clients/controller.rs
  duva/src/presentation/clients/request.rs
  duva/tests/client_ops/mod.rs
  duva/tests/client_ops/test_llen.rs
  duva/tests/client_ops/test_lrange.rs
Labels: refactoring, feat

#740 feat: lindex
  duva-client/src/broker/mod.rs
  duva-client/src/controller.rs
  duva/src/domains/caches/actor.rs
  duva/src/domains/caches/cache_manager.rs
  duva/src/domains/caches/cache_objects/types/quicklist.rs
  duva/src/domains/caches/command.rs
  duva/src/domains/caches/service.rs
  duva/src/domains/cluster_actors/topology.rs
  duva/src/domains/query_io.rs
  duva/src/presentation/clients/controller.rs
  duva/src/presentation/clients/request.rs
  duva/tests/client_ops/mod.rs
  duva/tests/client_ops/test_lindex.rs
Labels: feat

#743 feat: lset
  duva-client/src/controller.rs
  duva/src/domains/caches/actor.rs
  duva/src/domains/caches/cache_manager.rs
  duva/src/domains/caches/cache_objects/types/quicklist.rs
  duva/src/domains/caches/command.rs
  duva/src/domains/caches/service.rs
  duva/src/domains/operation_logs/operation.rs
  duva/src/presentation/clients/controller.rs
  duva/src/presentation/clients/request.rs
  duva/tests/client_ops/mod.rs
  duva/tests/client_ops/test_lset.rs
Labels: testability, feat

#745 feat: rpushx
  duva/src/domains/caches/actor.rs
  duva/src/domains/caches/cache_manager.rs
  duva/src/domains/caches/command.rs
  duva/src/domains/caches/service.rs
  duva/src/presentation/clients/controller.rs
  duva/src/presentation/clients/request.rs
  duva/tests/client_ops/mod.rs
  duva/tests/client_ops/test_rpushx.rs
Labels: testability, feat

#747 chore: cli hint for lpush rpush
  duva-client/src/cli/editor/completion.rs
  duva-client/src/cli/editor/hints.rs
Labels: chore

#749 chore: simplify command hint
  duva-client/src/cli/editor/hints.rs
Labels: chore

#750 refactor: consensus
  duva-client/src/broker/mod.rs
  duva-client/src/cli/editor/hints.rs
  duva/src/domains/caches/cache_manager.rs
  duva/src/domains/operation_logs/operation.rs
  duva/src/presentation/clients/controller.rs
  duva/src/presentation/clients/request.rs
  duva/src/presentation/clients/stream.rs
Labels: enhancement, refactoring

#751 feat: list nodes for keys returning replid: keys
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/command.rs
  duva/src/domains/cluster_actors/hash_ring.rs
Labels: enhancement, refactoring, feat

#756 fix: wrong pass of term
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/peers/command.rs
  duva/src/domains/peers/connections/connection_types.rs
  duva/src/domains/peers/mod.rs
  duva/src/domains/peers/peer.rs
Labels: bug

#758 feat: llen completion, hint for cli
  duva-client/src/cli/editor/completion.rs
  duva-client/src/cli/editor/hints.rs
  duva/src/domains/query_io.rs
Labels: feat

#761 fix: remove block write request when re-balancing started
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/actor/tests/partitionings.rs
Labels: bug

#763 refactor: simplify replication tracking
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/actor/tests/replications.rs
  duva/src/domains/cluster_actors/replication.rs
  duva/src/domains/cluster_actors/service.rs
  duva/src/domains/peers/command.rs
  duva/src/domains/peers/peer.rs
  duva/src/domains/query_io.rs
Labels: enhancement, testability, refactoring

#764 refactor: ack replication
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/actor/tests/replications.rs
Labels: testability, refactoring

#767 feat: cli - lpop,rpop
  duva-client/src/cli/editor/completion.rs
  duva-client/src/cli/editor/hints.rs
  duva/src/domains/cluster_actors/actor/client_sessions.rs
Labels: feat

#769 feat: lift up connection restriction
  duva/src/domains/cluster_actors/actor.rs
Labels: bug, feat
