Repository Migorithm/duva, pull requests merged in 2025-02, with the labels that each got.

#195 refactor: extract report liveness
  src/services/cluster/actors/listening_actor.rs
Labels: refactoring

#196 feat: peer state field
  src/services/cluster/actors/replication.rs
  src/services/cluster/actors/types.rs
  src/services/query_io.rs
  tests/test_replication_info.rs
Labels: testability, refactoring, feat

#197 refactor: improve testability
  src/client_utils/mod.rs
  src/services/cluster/actors/actor.rs
  src/services/cluster/actors/command.rs
  src/services/cluster/actors/listening_actor.rs
  tests/common.rs
  tests/test_clustering.rs
  tests/test_disseminate_peers.rs
  tests/test_handshake.rs
  tests/test_heartbeat.rs
  tests/test_load_sync_dump.rs
  tests/test_replication_info.rs
  tests/test_save_read_dump.rs
  tests/test_set_get.rs
Labels: testability, refactoring

#199 test: check_internodes_communication
  scripts.sh
  src/adapters/io/tokio_stream.rs
  src/lib.rs
  src/services/cluster/actors/actor.rs
  src/services/cluster/actors/listening_actor.rs
  src/services/cluster/actors/replication.rs
  src/services/cluster/actors/types.rs
  src/services/cluster/inbound/stream.rs
  src/services/cluster/manager.rs
  src/services/cluster/outbound/stream.rs
  src/services/config/init.rs
  src/services/query_io.rs
  tests/common.rs
  tests/test_clustering.rs
  tests/test_disseminate_peers.rs
  tests/test_handshake.rs
  tests/test_heartbeat.rs
  tests/test_replication_info.rs
  tests/test_save_read_dump.rs
Labels: bug, testability

#204 doc: gossip added
  README.md
Labels: documentation

#206 feat: cluster forget command operation
  src/services/client/manager.rs
  src/services/client/request.rs
  src/services/client/stream.rs
  src/services/cluster/actors/actor.rs
  src/services/cluster/actors/command.rs
  src/services/cluster/actors/mod.rs
  src/services/cluster/manager.rs
  tests/test_cluster_forget.rs
Labels: testability, feat

#208 refactor: remove TStream
  src/adapters/io/tokio_stream.rs
  src/services/client/manager.rs
  src/services/cluster/actors/actor.rs
  src/services/cluster/inbound/stream.rs
  src/services/cluster/outbound/stream.rs
  src/services/interface.rs
  src/services/query_io.rs
Labels: refactoring

#209 rm: cancellation token
  src/adapters/cancellation_token.rs
  src/adapters/mod.rs
  src/lib.rs
  src/main.rs
  src/services/client/manager.rs
  src/services/cluster/inbound/stream.rs
  src/services/interface.rs
  src/services/statefuls/persist/endec/encoder/byte_encoder.rs
  tests/test_config_get_dir.rs
Labels: refactoring, kill legacy

#210 refactor: extract client stream handler
  src/lib.rs
  src/services/client/manager.rs
Labels: enhancement, refactoring

#216 test: graceful shutdown for zombie process
  tests/common.rs
  tests/test_save_read_dump.rs
Labels: testability

#219 feat: ban list for cluster forget propagation
  src/services/cluster/actors/actor.rs
  src/services/cluster/command/cluster_command.rs
  src/services/cluster/peers/mod.rs
  src/services/cluster/peers/peer.rs
  tests/common.rs
Labels: refactoring, feat

#222 feat: remove nodes based on ban list
  src/services/cluster/actors/actor.rs
  src/services/cluster/replications/replication.rs
Labels: enhancement, feat

#223 test: cluster-wide forget operation propagation
  src/services/cluster/peers/address.rs
  tests/common.rs
  tests/test_cluster_forget.rs
Labels: enhancement, testability

#225 fix: abrupt system exit
  src/services/cluster/actors/actor.rs
  src/services/cluster/manager.rs
Labels: bug, enhancement

#226 feat: remove ban_list constraint from add peer
  src/services/cluster/actors/actor.rs
  src/services/cluster/manager.rs
  src/services/cluster/replications/replication.rs
  src/services/query_io.rs
Labels: refactoring, feat

#227 feat: recovery connection on reconnection
  scripts.sh
  src/client_utils/mod.rs
  src/services/cluster/actors/actor.rs
  src/services/cluster/peers/identifier.rs
Labels: bug, feat

#228 doc: readme updated
  README.md
Labels: documentation

#229 doc: readme updated
  README.md
Labels: documentation

#230 doc:replication happy case
  README.md
  diagrams/raft-replication-happycase.png
Labels: documentation

#231 doc: readindex for linearizability
  diagrams/raft(1)-replication.png
  diagrams/raft(2)-readindex.png
Labels: documentation

#232 feat: raft replication happypath outlined
  src/services/client/manager.rs
  src/services/client/request.rs
  src/services/client/stream.rs
  src/services/cluster/actors/actor.rs
  src/services/cluster/command/cluster_command.rs
  src/services/cluster/inbound/stream.rs
  src/services/cluster/manager.rs
  src/services/cluster/outbound/stream.rs
  src/services/cluster/peers/kind.rs
  src/services/cluster/replications/replication.rs
  src/services/query_io.rs
  src/services/statefuls/cache/manager.rs
  src/services/statefuls/persist/endec/encoder/encoding_processor.rs
Labels: refactoring, feat

#233 feat: raft critical commit section
  src/services/client/manager.rs
  src/services/cluster/actors/actor.rs
  src/services/cluster/command/cluster_command.rs
  src/services/cluster/manager.rs
Labels: feat

#234 feat: operation log
  src/adapters/aof/local_aof.rs
  src/services/aof.rs
  src/services/client/manager.rs
  src/services/client/request.rs
  src/services/cluster/actors/actor.rs
  src/services/cluster/command/cluster_command.rs
  src/services/query_io.rs
Labels: enhancement, refactoring, feat

#235 refactor: set convertor moved to write request
  src/adapters/aof/local_aof.rs
  src/services/aof.rs
  src/services/client/manager.rs
  src/services/cluster/actors/actor.rs
  src/services/cluster/command/cluster_command.rs
  src/services/query_io.rs
Labels: refactoring

#237 refactor: persist directory
  src/lib.rs
  src/services/client/manager.rs
  src/services/cluster/inbound/stream.rs
  src/services/statefuls/cache/actor.rs
  src/services/statefuls/cache/manager.rs
  src/services/statefuls/mod.rs
  src/services/statefuls/persist/endec/encoder/mod.rs
  src/services/statefuls/snapshot/dump_file.rs
  src/services/statefuls/snapshot/dump_loader.rs
  src/services/statefuls/snapshot/endec/decoder/byte_decoder.rs
  src/services/statefuls/snapshot/endec/decoder/mod.rs
  src/services/statefuls/snapshot/endec/decoder/states.rs
  src/services/statefuls/snapshot/endec/encoder/byte_encoder.rs
  src/services/statefuls/snapshot/endec/encoder/mod.rs
  src/services/statefuls/snapshot/endec/mod.rs
  src/services/statefuls/snapshot/mod.rs
  src/services/statefuls/snapshot/save/actor.rs
  src/services/statefuls/snapshot/save/command.rs
  src/services/statefuls/snapshot/save/mod.rs
Labels: refactoring

#242 feat : actor registry
  src/adapters/io/mod.rs
  src/adapters/io/tokio_file.rs
  src/lib.rs
  src/main.rs
  src/services/actor_registry.rs
  src/services/client/manager.rs
  src/services/cluster/inbound/stream.rs
  src/services/cluster/manager.rs
  src/services/interface.rs
  src/services/mod.rs
  src/services/statefuls/cache/actor.rs
  src/services/statefuls/cache/manager.rs
  src/services/statefuls/cache/ttl/actor.rs
  src/services/statefuls/cache/ttl/manager.rs
  src/services/statefuls/snapshot/endec/decoder/byte_decoder.rs
  src/services/statefuls/snapshot/mod.rs
  src/services/statefuls/snapshot/save/actor.rs
  src/services/statefuls/snapshot/save/mod.rs
Labels: refactoring, feat

#243 fix: visibility on cache actor
  src/lib.rs
  src/services/statefuls/cache/manager.rs
Labels: bug

#244 feat: append entry for logging
  src/services/aof.rs
  src/services/cluster/actors/actor.rs
  src/services/cluster/actors/listening_actor.rs
  src/services/cluster/command/cluster_command.rs
  src/services/cluster/command/listening_command.rs
  src/services/cluster/replications/replication.rs
  src/services/query_io.rs
Labels: refactoring, feat

#245 feat: consensus logging outlined
  src/adapters/io/tokio_stream.rs
  src/services/cluster/actors/actor.rs
  src/services/cluster/actors/listening_actor.rs
  src/services/cluster/command/cluster_command.rs
  src/services/cluster/command/listening_command.rs
  src/services/cluster/peers/peer.rs
  src/services/cluster/replications/replication.rs
  src/services/interface.rs
  src/services/query_io.rs
Labels: bug, testability, refactoring, feat

#246 feat: fully concurrent, unordered execution
  Cargo.lock
  Cargo.toml
  src/services/cluster/actors/actor.rs
  src/services/cluster/replications/replication.rs
Labels: enhancement, feat

#247 fix: tasks regeneration
  src/services/client/manager.rs
  src/services/cluster/actors/actor.rs
  src/services/cluster/command/cluster_command.rs
Labels: bug

#248 refactor: presentation layer
  src/actor_registry.rs
  src/init.rs
  src/lib.rs
  src/presentation/client_in/manager.rs
  src/presentation/client_in/mod.rs
  src/presentation/client_in/request.rs
  src/presentation/client_in/stream.rs
  src/presentation/cluster_in/communication_manager.rs
  src/presentation/cluster_in/connection_broker.rs
  src/presentation/cluster_in/inbound/arguments.rs
  src/presentation/cluster_in/inbound/mod.rs
  src/presentation/cluster_in/inbound/request.rs
  src/presentation/cluster_in/inbound/stream.rs
  src/presentation/cluster_in/mod.rs
  src/presentation/cluster_in/outbound/mod.rs
  src/presentation/cluster_in/outbound/response.rs
  src/presentation/cluster_in/outbound/stream.rs
  src/presentation/cluster_in/peer_listeners/mod.rs
  src/presentation/cluster_in/peer_listeners/peer_listener.rs
  src/presentation/cluster_in/peer_listeners/requests.rs
  src/presentation/mod.rs
  src/services/actor_registry.rs
  src/services/aof.rs
  src/services/client/request.rs
  src/services/cluster/actors/actor.rs
  src/services/cluster/actors/commands.rs
  src/services/cluster/actors/mod.rs
  src/services/cluster/command/mod.rs
  src/services/cluster/manager.rs
  src/services/cluster/mod.rs
  src/services/cluster/outbound/mod.rs
  src/services/cluster/peers/peer.rs
  src/services/cluster/replications/replication.rs
  src/services/config/actor.rs
  src/services/config/manager.rs
  src/services/config/mod.rs
  src/services/mod.rs
Labels: refactoring

#250 doc: actor postfix
  README.md
  src/presentation/cluster_in/mod.rs
  src/presentation/cluster_in/peer_listeners/peer_listener.rs
Labels: documentation

#252 refactor: env injection
  src/init.rs
  src/lib.rs
  src/main.rs
  src/presentation/cluster_in/communication_manager.rs
  src/services/aof.rs
  src/services/cluster/actors/actor.rs
  src/services/cluster/replications/replication.rs
  src/services/config/actor.rs
  src/services/config/manager.rs
  src/services/query_io.rs
  tests/common.rs
Labels: enhancement, testability, refactoring

#253 feat: recv-full-sync
  .gitignore
  Cargo.lock
  Cargo.toml
  Makefile
  src/actor_registry.rs
  src/lib.rs
  src/main.rs
  src/presentation/client_in/manager.rs
  src/presentation/cluster_in/communication_manager.rs
  src/presentation/cluster_in/connection_manager.rs
  src/presentation/cluster_in/inbound/stream.rs
  src/presentation/cluster_in/mod.rs
  src/presentation/cluster_in/outbound/stream.rs
  src/presentation/cluster_in/peer_listeners/peer_listener.rs
  src/presentation/cluster_in/peer_listeners/requests.rs
  src/services/cluster/actors/actor.rs
  src/services/statefuls/cache/manager.rs
  src/services/statefuls/snapshot/dump_loader.rs
  src/services/statefuls/snapshot/endec/decoder/byte_decoder.rs
  src/services/statefuls/snapshot/endec/decoder/states.rs
  src/services/statefuls/snapshot/mod.rs
  src/services/statefuls/snapshot/save/actor.rs
  src/services/statefuls/snapshot/snapshot.rs
  src/services/statefuls/snapshot/snapshot_applier.rs
  src/services/statefuls/snapshot/snapshot_loader.rs
  tests/common.rs
  tests/test_recv_full_sync.rs
  tests/test_save_read_snapshot.rs
Labels: feat

#254 feat: master repl offset
  src/presentation/client_in/manager.rs
  src/services/cluster/actors/actor.rs
  src/services/cluster/replications/replication.rs
Labels: enhancement, feat

#255 feat: raft happy path
  src/client_utils/mod.rs
  src/presentation/client_in/manager.rs
  src/presentation/cluster_in/communication_manager.rs
  src/presentation/cluster_in/peer_listeners/peer_listener.rs
  src/presentation/cluster_in/peer_listeners/requests.rs
  src/services/cluster/actors/actor.rs
  src/services/cluster/actors/commands.rs
  src/services/cluster/actors/consensus.rs
  src/services/cluster/actors/mod.rs
  src/services/cluster/replications/replication.rs
  src/services/query_io.rs
  tests/test_config_get_dir.rs
Labels: enhancement, feat

#259 renaming : give more meaning to command variants.
  src/presentation/client_in/manager.rs
  src/presentation/cluster_in/peer_listeners/peer_listener.rs
  src/services/cluster/actors/actor.rs
  src/services/cluster/actors/commands.rs
Labels: refactoring

#260 refactor: cluster listener as state machine
  src/init.rs
  src/lib.rs
  src/presentation/client_in/manager.rs
  src/presentation/cluster_in/communication_manager.rs
  src/presentation/cluster_in/connection_manager.rs
  src/presentation/cluster_in/inbound/stream.rs
  src/presentation/cluster_in/mod.rs
  src/presentation/cluster_in/outbound/stream.rs
  src/presentation/cluster_in/peer_listeners/mod.rs
  src/presentation/cluster_in/peer_listeners/peer_listener.rs
  src/presentation/cluster_in/peer_listeners/requests.rs
  src/services/cluster/actors/actor.rs
  src/services/cluster/actors/commands.rs
  src/services/cluster/actors/mod.rs
  src/services/cluster/actors/replication.rs
  src/services/cluster/actors/replid_generator.rs
  src/services/cluster/listeners/follower.rs
  src/services/cluster/listeners/leader.rs
  src/services/cluster/listeners/mod.rs
  src/services/cluster/listeners/non_data_peer.rs
  src/services/cluster/mod.rs
  src/services/cluster/peers/address.rs
  src/services/cluster/peers/connected_types.rs
  src/services/cluster/peers/kind.rs
  src/services/cluster/peers/mod.rs
  src/services/cluster/peers/peer.rs
  src/services/cluster/replications/mod.rs
  src/services/query_io.rs
  src/services/statefuls/cache/actor.rs
  src/services/statefuls/cache/manager.rs
  src/services/statefuls/cache/ttl/manager.rs
  src/services/statefuls/snapshot/save/actor.rs
  src/services/statefuls/snapshot/snapshot_applier.rs
Labels: enhancement, refactoring

#262 refactor: simplify creation of peer
  src/presentation/cluster_in/inbound/stream.rs
  src/presentation/cluster_in/mod.rs
  src/presentation/cluster_in/outbound/stream.rs
  src/services/cluster/peers/connected_types.rs
  src/services/cluster/peers/peer.rs
Labels: enhancement, refactoring

#263 refactor: rename master/slave -> leader/follower
  Makefile
  README.md
  diagrams/clustering.mmd
  src/init.rs
  src/lib.rs
  src/presentation/client_in/manager.rs
  src/presentation/cluster_in/connection_manager.rs
  src/presentation/cluster_in/inbound/stream.rs
  src/presentation/cluster_in/outbound/stream.rs
  src/services/cluster/actors/actor.rs
  src/services/cluster/actors/commands.rs
  src/services/cluster/actors/replication.rs
  src/services/cluster/listeners/follower.rs
  src/services/cluster/listeners/leader.rs
  src/services/cluster/peers/kind.rs
  src/services/cluster/peers/peer.rs
  src/services/query_io.rs
  tests/common.rs
  tests/test_cluster_forget.rs
  tests/test_clustering.rs
  tests/test_disseminate_peers.rs
  tests/test_heartbeat.rs
  tests/test_recv_full_sync.rs
  tests/test_save_read_snapshot.rs
Labels: refactoring

#265 refactor: mv env macro
  src/domains/config_actors/conf_macros.rs
  src/domains/config_actors/mod.rs
  src/macros.rs
Labels: refactoring

#266 test: separate tests to prevent port collision
  tests/test_cluster_forget_node_propagation.rs
  tests/test_cluster_forget_when_wrong_id_given.rs
Labels: bug, testability

#267 test : raft happy case added
  src/domains/cluster_actors/actor.rs
  tests/common.rs
  tests/test_cluster_forget_node_propagation.rs
  tests/test_clustering.rs
  tests/test_disseminate_peers.rs
  tests/test_heartbeat.rs
  tests/test_raft_happy_case.rs
  tests/test_recv_full_sync.rs
Labels: testability, refactoring

#268 feat: AcceptLeaderHeartBeat
  src/domains/cluster_actors/actor.rs
  src/domains/cluster_actors/commands.rs
  src/domains/cluster_actors/consensus.rs
  src/domains/cluster_actors/replication.rs
  src/domains/cluster_listeners/mod.rs
  src/presentation/clients/controller.rs
  src/presentation/listeners/leader.rs
  src/services/handlers/cluster.rs
  tests/test_raft_happy_case.rs
Labels: enhancement, testability, feat

#269 test: timed_wait_for_message accepts vector of string
  tests/common.rs
  tests/test_cluster_forget_node_propagation.rs
  tests/test_raft_happy_case.rs
Labels: testability, refactoring

#270 refactor LogIndex should be replaced with TransactionLogging
  src/adapters/aof/local_aof.rs
  src/domains/append_only_files/log.rs
  src/domains/cluster_actors/actor.rs
  src/domains/cluster_actors/commands.rs
  src/domains/cluster_actors/consensus.rs
  src/domains/cluster_actors/replication.rs
  src/domains/query_parsers/query_io.rs
  src/presentation/clients/controller.rs
  src/presentation/listeners/follower.rs
  src/presentation/listeners/leader.rs
  src/services/handlers/cluster.rs
Labels: bug

#272 refactor: client acceptor / controller
  src/actor_registry.rs
  src/adapters/aof/local_aof.rs
  src/adapters/io/tokio_stream.rs
  src/domains/append_only_files/log.rs
  src/domains/cluster_actors/mod.rs
  src/domains/peers/peer.rs
  src/domains/query_parsers/mod.rs
  src/domains/query_parsers/query_io.rs
  src/domains/saves/actor.rs
  src/domains/saves/endec/decoder/byte_decoder.rs
  src/domains/saves/endec/encoder/byte_encoder.rs
  src/lib.rs
  src/main.rs
  src/presentation/clients/controller.rs
  src/presentation/clients/controllers/acceptor.rs
  src/presentation/clients/controllers/handler.rs
  src/presentation/clients/controllers/mod.rs
  src/presentation/clients/mod.rs
  src/presentation/cluster_in/communication_manager.rs
  src/presentation/cluster_in/connection_manager.rs
  src/presentation/listeners/leader.rs
Labels: enhancement, refactoring

#274 optimization: parsing
  src/domains/query_parsers/mod.rs
  src/domains/query_parsers/parsing_context.rs
  src/domains/query_parsers/query_io.rs
  tests/test_cluster_known_nodes_increase_when_new_replica_is_added.rs
  tests/test_removes_node_when_heartbeat_is_not_received_for_certain_time.rs
Labels: enhancement, refactoring

#275 test-fix: port collision
  tests/common.rs
  tests/test_replication_info.rs
Labels: bug, testability

#280 test: acceptance range for dynamic port
  src/presentation/clients/controllers/acceptor.rs
  src/presentation/clients/controllers/handler.rs
  src/services/handlers/cluster.rs
  tests/common.rs
Labels: bug, testability

#281 feat: integrate logger
  src/domains/append_only_files/interfaces.rs
  src/domains/append_only_files/log.rs
  src/domains/append_only_files/logger.rs
  src/domains/append_only_files/mod.rs
  src/domains/cluster_actors/actor.rs
  src/domains/saves/endec/decoder/byte_decoder.rs
  src/domains/saves/endec/encoder/byte_encoder.rs
  src/lib.rs
  src/main.rs
  src/presentation/cluster_in/communication_manager.rs
  src/services/handlers/cluster.rs
  src/services/interface.rs
  tests/test_raft_happy_case.rs
Labels: enhancement, testability, refactoring, feat

#286 test: file name injection
  src/domains/saves/actor.rs
  src/domains/saves/endec/mod.rs
  tests/common.rs
  tests/test_cluster_forget_node_propagation.rs
  tests/test_cluster_forget_when_wrong_id_given.rs
  tests/test_cluster_known_nodes_increase_when_new_replica_is_added.rs
  tests/test_config_get_dir.rs
  tests/test_disseminate_peers.rs
  tests/test_heartbeat.rs
  tests/test_keys.rs
  tests/test_raft_happy_case.rs
  tests/test_recv_full_sync.rs
  tests/test_removes_node_when_heartbeat_is_not_received_for_certain_time.rs
  tests/test_replication_info.rs
  tests/test_save_read_snapshot.rs
  tests/test_set_get.rs
Labels: testability, refactoring

#288 feat: follower logging
  src/domains/cluster_actors/actor.rs
  src/services/handlers/cluster.rs
  tests/common.rs
  tests/test_cluster_forget_node_propagation.rs
  tests/test_cluster_known_nodes_increase_when_new_replica_is_added.rs
  tests/test_disseminate_peers.rs
  tests/test_heartbeat.rs
  tests/test_raft_happy_case.rs
  tests/test_recv_full_sync.rs
  tests/test_removes_node_when_heartbeat_is_not_received_for_certain_time.rs
Labels: testability, refactoring, feat

#289 feat: inject cache manager to cluster actor
  src/domains/cluster_actors/actor.rs
  src/lib.rs
  src/presentation/cluster_in/communication_manager.rs
  src/services/handlers/cluster.rs
  tests/test_raft_happy_case.rs
Labels: refactoring, feat

#290 feat: follower state change outlined
  src/adapters/aof/local_aof.rs
  src/domains/append_only_files/interfaces.rs
  src/domains/append_only_files/log.rs
  src/domains/append_only_files/logger.rs
  src/domains/caches/cache_manager.rs
  src/domains/cluster_actors/actor.rs
  src/domains/cluster_actors/replication.rs
  src/domains/query_parsers/query_io.rs
  src/lib.rs
  src/presentation/clients/controllers/handler.rs
  src/services/handlers/cluster.rs
  tests/test_raft_happy_case.rs
Labels: refactoring, feat

#292 test: file clean up
  tests/common.rs
  tests/test_cluster_forget_node_propagation.rs
  tests/test_cluster_forget_when_wrong_id_given.rs
  tests/test_cluster_known_nodes_increase_when_new_replica_is_added.rs
  tests/test_config_get_dir.rs
  tests/test_disseminate_peers.rs
  tests/test_heartbeat.rs
  tests/test_keys.rs
  tests/test_raft_happy_case.rs
  tests/test_recv_full_sync.rs
  tests/test_removes_node_when_heartbeat_is_not_received_for_certain_time.rs
  tests/test_replication_info.rs
  tests/test_save_read_snapshot.rs
  tests/test_set_get.rs
Labels: testability

#293 test: server env for test
  tests/common.rs
  tests/test_cluster_forget_node_propagation.rs
  tests/test_cluster_forget_when_wrong_id_given.rs
  tests/test_cluster_known_nodes_increase_when_new_replica_is_added.rs
  tests/test_config_get_dir.rs
  tests/test_disseminate_peers.rs
  tests/test_heartbeat.rs
  tests/test_keys.rs
  tests/test_raft_happy_case.rs
  tests/test_recv_full_sync.rs
  tests/test_removes_node_when_heartbeat_is_not_received_for_certain_time.rs
  tests/test_replication_info.rs
  tests/test_save_read_snapshot.rs
  tests/test_set_get.rs
Labels: testability

#295 feat: inmemory aof impl
  src/adapters/aof/local_aof.rs
  src/adapters/aof/memory_aof.rs
  src/adapters/aof/mod.rs
  src/domains/append_only_files/interfaces.rs
  src/domains/append_only_files/log.rs
  src/domains/append_only_files/logger.rs
  src/domains/caches/cache_manager.rs
  src/domains/caches/command.rs
  src/domains/cluster_actors/actor.rs
  src/init.rs
  src/main.rs
  src/services/handlers/cluster.rs
  tests/common.rs
Labels: feat

#303 feat: follower
  src/adapters/aof/local_aof.rs
  src/adapters/aof/memory_aof.rs
  src/domains/append_only_files/interfaces.rs
  src/domains/append_only_files/logger.rs
  src/domains/cluster_actors/actor.rs
  src/domains/cluster_actors/replication.rs
  src/services/handlers/cluster.rs
Labels: refactoring, feat

#304 readme: partial sync
  README.md
  diagrams/partial_sync.mmd
Labels: documentation

#306 refactor: encapsulate replicate
  src/domains/cluster_actors/actor.rs
  src/services/handlers/cluster.rs
Labels: refactoring

#307 mv : consensus_con
  src/domains/cluster_actors/actor.rs
  src/domains/cluster_actors/consensus.rs
  src/services/handlers/cluster.rs
Labels: refactoring

#308 fix: bug fix on commit
  src/domains/cluster_actors/actor.rs
  src/lib.rs
  src/presentation/cluster_in/communication_manager.rs
  src/services/handlers/cluster.rs
Labels: bug

#309 test: unittest on follower replication
  src/domains/caches/actor.rs
  src/domains/caches/cache_manager.rs
  src/domains/cluster_actors/actor.rs
  src/domains/peers/peer.rs
  src/domains/saves/snapshot/snapshot_applier.rs
  src/lib.rs
  src/services/handlers/cluster.rs
Labels: testability, refactoring

#310 formatter applied
  rustfmt.toml
  src/adapters/io/tokio_stream.rs
  src/domains/append_only_files/log.rs
  src/domains/caches/actor.rs
  src/domains/caches/cache_manager.rs
  src/domains/caches/cache_objects.rs
  src/domains/cluster_actors/actor.rs
  src/domains/config_actors/config_manager.rs
  src/domains/peers/identifier.rs
  src/domains/peers/peer.rs
  src/domains/query_parsers/query_io.rs
  src/domains/saves/actor.rs
  src/domains/saves/endec/decoder/byte_decoder.rs
  src/domains/saves/endec/encoder/byte_encoder.rs
  src/domains/saves/endec/mod.rs
  src/lib.rs
  src/presentation/clients/controllers/acceptor.rs
  src/presentation/clients/controllers/handler.rs
  src/presentation/clients/request.rs
  src/presentation/clients/stream.rs
  src/presentation/cluster_in/connection_manager.rs
  src/presentation/cluster_in/inbound/request.rs
  src/presentation/cluster_in/inbound/stream.rs
  src/presentation/cluster_in/outbound/response.rs
  src/presentation/cluster_in/outbound/stream.rs
  src/presentation/listeners/follower.rs
  src/presentation/listeners/leader.rs
  src/services/handlers/cache.rs
  src/services/handlers/cluster.rs
  src/services/handlers/config.rs
  src/services/handlers/save.rs
Labels: refactoring

#311 test: from lowest logs, follower specific heertbeat
  src/domains/cluster_actors/actor.rs
Labels: testability, refactoring
