Repository Migorithm/duva, pull requests merged in 2025-05, with the labels that each got.

#528 feat: centralize request id updating logics
  duva-client/src/broker/mod.rs
  duva-client/src/controller.rs
  duva/src/domains/caches/cache_manager.rs
Labels: enhancement, refactoring

#529 feat: outline consistent hashing
  duva-client/src/broker/mod.rs
  duva/src/domains/caches/cache_manager.rs
  duva/src/domains/cluster_actors/hash_ring.rs
  duva/src/domains/cluster_actors/mod.rs
Labels: feat

#531 refactor: cache entry
  duva/src/domains/caches/actor.rs
  duva/src/domains/caches/cache_manager.rs
  duva/src/domains/caches/cache_objects.rs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/saves/endec/decoder/byte_decoder.rs
  duva/src/domains/saves/endec/encoder/byte_encoder.rs
  duva/src/services/handlers/cache.rs
Labels: refactoring

#532 refactor: flatten endec
  duva/src/domains/saves/actor.rs
  duva/src/domains/saves/endec/decoder.rs
  duva/src/domains/saves/endec/decoder/mod.rs
  duva/src/domains/saves/endec/decoder/states.rs
  duva/src/domains/saves/endec/encoder.rs
  duva/src/domains/saves/endec/encoder/mod.rs
  duva/src/domains/saves/endec/mod.rs
  duva/src/domains/saves/snapshot/snapshot_loader.rs
Labels: refactoring

#534 run integrated tests with and without disk-based append only files
  duva/src/adapters/op_logs/disk_based.rs
  duva/src/adapters/op_logs/memory_based.rs
  duva/src/domains/operation_logs/interfaces.rs
  duva/tests/client_ops/test_config_get_dir.rs
  duva/tests/client_ops/test_decr.rs
  duva/tests/client_ops/test_del.rs
  duva/tests/client_ops/test_exists.rs
  duva/tests/client_ops/test_incr.rs
  duva/tests/client_ops/test_keys.rs
  duva/tests/client_ops/test_replication_info.rs
  duva/tests/client_ops/test_set_get.rs
  duva/tests/client_ops/test_snapshot_persists_and_recovers_state.rs
  duva/tests/client_ops/test_ttl.rs
  duva/tests/cluster_ops/test_cluster_forget_makes_all_nodes_forget_target_node.rs
  duva/tests/cluster_ops/test_cluster_forget_when_wrong_id_given.rs
  duva/tests/cluster_ops/test_cluster_known_nodes_increase_when_new_replica_is_added.rs
  duva/tests/cluster_ops/test_heartbeat.rs
  duva/tests/cluster_ops/test_lazy_discovery.rs
  duva/tests/cluster_ops/test_reconnection_on_reboot.rs
  duva/tests/cluster_ops/test_removes_node_when_heartbeat_is_not_received_for_certain_time.rs
  duva/tests/common.rs
  duva/tests/replication_ops/test_leader_election.rs
  duva/tests/replication_ops/test_raft_happy_case.rs
  duva/tests/replication_ops/test_sync.rs
Labels: testability

#535 docs: consistent-hashing sequence diagram for server side operation
  diagrams/consistent-hashing-client.mmd
  diagrams/consistent-hashing-server.mmd
Labels: documentation

#536 feat: get token ranges / take subset
  duva/src/domains/caches/actor.rs
  duva/src/domains/cluster_actors/hash_ring.rs
Labels: testability, feat

#538 feat: cli - cluster meet
  duva-client/src/cli/editor/completion.rs
  duva-client/src/cli/editor/hints.rs
  duva-client/src/controller.rs
  duva/src/presentation/clients/controller.rs
  duva/src/presentation/clients/request.rs
Labels: feat

#541 feat: optimize incr-decr
  duva/src/domains/caches/actor.rs
  duva/src/domains/caches/cache_manager.rs
  duva/src/domains/caches/command.rs
  duva/src/services/handlers/cache.rs
Labels: feat

#539 feat: delaying client requests
  diagrams/consistent-hashing-server.mmd
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/commands/cluster_actor_command.rs
  duva/src/domains/cluster_actors/commands/mod.rs
  duva/src/presentation/clients/controller.rs
  duva/src/services/handlers/cluster.rs
Labels: feat

#543 feat: partial sync and log reconcilation
  README.md
  diagrams/partial_sync.mmd
  duva/src/domains/caches/cache_manager.rs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/operation_logs/interfaces.rs
  duva/src/domains/operation_logs/logger.rs
  duva/src/domains/operation_logs/operation.rs
  duva/src/presentation/clients/request.rs
  duva/src/services/handlers/cluster.rs
  duva/tests/cluster_ops/test_reconnection_on_reboot.rs
Labels: bug, testability, refactoring, feat

#545 feat: tracing on client requests
  Cargo.lock
  duva/Cargo.toml
  duva/src/domains/caches/cache_manager.rs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/heartbeats/scheduler.rs
  duva/src/domains/cluster_actors/listener.rs
  duva/src/domains/config_actors/config_manager.rs
  duva/src/domains/operation_logs/logger.rs
  duva/src/lib.rs
  duva/src/main.rs
  duva/src/presentation/clients/controller.rs
  duva/src/presentation/clients/stream.rs
  duva/src/presentation/clusters/communication_manager.rs
  duva/tests/client_ops/test_keys.rs
  duva/tests/common.rs
  duva/tests/replication_ops/test_raft_happy_case.rs
Labels: enhancement

#546 test limit set for further investigration
  duva/tests/client_ops/test_keys.rs
Labels: bug

#547 refactor: cache actor logics
  duva/src/domains/caches/actor.rs
  duva/src/domains/caches/cache_manager.rs
  duva/src/presentation/clients/controller.rs
  duva/src/services/handlers/cache.rs
Labels: refactoring

#549 optimize : RAFT - liveness property on data synchronization
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/commands/cluster_actor_command.rs
  duva/src/domains/cluster_actors/commands/peer_listener_command.rs
  duva/src/domains/cluster_actors/listener.rs
  duva/src/domains/cluster_actors/peer_connections/inbound/stream.rs
  duva/src/domains/operation_logs/logger.rs
  duva/src/lib.rs
  duva/src/presentation/clients/controller.rs
  duva/src/presentation/clusters/communication_manager.rs
  duva/src/services/handlers/cluster.rs
  duva/tests/client_ops/test_snapshot_persists_and_recovers_state.rs
  duva/tests/cluster_ops/test_cluster_known_nodes_increase_when_new_replica_is_added.rs
  duva/tests/cluster_ops/test_lazy_discovery.rs
  duva/tests/replication_ops/test_raft_happy_case.rs
Labels: bug, enhancement, testability, refactoring

#552 bug: zombie process due to async-based test
  duva-client/src/broker/mod.rs
  duva-client/src/cli/main.rs
  duva-client/src/controller.rs
  duva/src/domains/cluster_actors/hash_ring.rs
  duva/tests/client_ops/test_append.rs
  duva/tests/client_ops/test_config_get_dir.rs
  duva/tests/client_ops/test_decr.rs
  duva/tests/client_ops/test_del.rs
  duva/tests/client_ops/test_exists.rs
  duva/tests/client_ops/test_incr.rs
  duva/tests/client_ops/test_keys.rs
  duva/tests/client_ops/test_replication_info.rs
  duva/tests/client_ops/test_set_get.rs
  duva/tests/client_ops/test_snapshot_persists_and_recovers_state.rs
  duva/tests/client_ops/test_ttl.rs
  duva/tests/cluster_ops/test_cluster_forget_makes_all_nodes_forget_target_node.rs
  duva/tests/cluster_ops/test_cluster_forget_when_wrong_id_given.rs
  duva/tests/cluster_ops/test_cluster_known_nodes_increase_when_new_replica_is_added.rs
  duva/tests/cluster_ops/test_heartbeat.rs
  duva/tests/cluster_ops/test_lazy_discovery.rs
  duva/tests/cluster_ops/test_reconnection_on_reboot.rs
  duva/tests/cluster_ops/test_removes_node_when_heartbeat_is_not_received_for_certain_time.rs
  duva/tests/common.rs
  duva/tests/replication_ops/test_leader_election.rs
  duva/tests/replication_ops/test_raft_happy_case.rs
  duva/tests/replication_ops/test_sync.rs
Labels: bug, testability

#553 feat: block invalid operation on self
  duva-client/src/cli/editor/completion.rs
  duva-client/src/cli/editor/hints.rs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/commands/cluster_actor_command.rs
  duva/src/domains/cluster_actors/replication.rs
  duva/src/macros.rs
  duva/src/presentation/clients/controller.rs
  duva/src/presentation/clients/stream.rs
  duva/src/presentation/clusters/communication_manager.rs
  duva/src/services/handlers/cluster.rs
  duva/tests/cluster_ops/test_lazy_discovery.rs
Labels: testability, feat

#554 test: refactoring for better understanding
  duva/src/domains/caches/actor.rs
  duva/tests/cluster_ops/test_cluster_forget_makes_all_nodes_forget_target_node.rs
  duva/tests/cluster_ops/test_cluster_forget_when_wrong_id_given.rs
  duva/tests/cluster_ops/test_cluster_known_nodes_increase_when_new_replica_is_added.rs
  duva/tests/cluster_ops/test_heartbeat.rs
  duva/tests/cluster_ops/test_reconnection_on_reboot.rs
  duva/tests/cluster_ops/test_removes_node_when_heartbeat_is_not_received_for_certain_time.rs
  duva/tests/common.rs
  duva/tests/replication_ops/test_leader_election.rs
  duva/tests/replication_ops/test_raft_happy_case.rs
  duva/tests/replication_ops/test_sync.rs
Labels: testability, refactoring

#555 test: diable piped io to prevent burst
  duva/tests/client_ops/test_incr.rs
  duva/tests/client_ops/test_set_get.rs
  duva/tests/client_ops/test_snapshot_persists_and_recovers_state.rs
  duva/tests/cluster_ops/test_cluster_forget_makes_all_nodes_forget_target_node.rs
  duva/tests/cluster_ops/test_cluster_forget_when_wrong_id_given.rs
  duva/tests/cluster_ops/test_cluster_known_nodes_increase_when_new_replica_is_added.rs
  duva/tests/cluster_ops/test_lazy_discovery.rs
  duva/tests/cluster_ops/test_reconnection_on_reboot.rs
  duva/tests/cluster_ops/test_removes_node_when_heartbeat_is_not_received_for_certain_time.rs
  duva/tests/common.rs
  duva/tests/replication_ops/test_leader_election.rs
  duva/tests/replication_ops/test_raft_happy_case.rs
  duva/tests/replication_ops/test_sync.rs
Labels: testability, refactoring

#556 feat: add INCRBY and DECRBY commands
  docs/_commands/decrby.md
  docs/_commands/incrby.md
  duva-client/src/broker/mod.rs
  duva-client/src/cli/editor/completion.rs
  duva-client/src/cli/editor/hints.rs
  duva-client/src/controller.rs
  duva/src/domains/caches/actor.rs
  duva/src/domains/caches/cache_manager.rs
  duva/src/presentation/clients/controller.rs
  duva/src/presentation/clients/request.rs
  duva/src/presentation/clients/stream.rs
  duva/tests/client_ops/mod.rs
  duva/tests/client_ops/test_decr.rs
  duva/tests/client_ops/test_decrby.rs
  duva/tests/client_ops/test_incr.rs
  duva/tests/client_ops/test_incrby.rs
Labels: bug, testability, refactoring, feat

#558 test: cnt not requiring helper method
  Cargo.lock
  duva/Cargo.toml
  duva/src/presentation/clients/stream.rs
  duva/tests/client_ops/test_append.rs
  duva/tests/client_ops/test_config_get_dir.rs
  duva/tests/client_ops/test_decr.rs
  duva/tests/client_ops/test_decrby.rs
  duva/tests/client_ops/test_del.rs
  duva/tests/client_ops/test_exists.rs
  duva/tests/client_ops/test_incr.rs
  duva/tests/client_ops/test_incrby.rs
  duva/tests/client_ops/test_keys.rs
  duva/tests/client_ops/test_replication_info.rs
  duva/tests/client_ops/test_set_get.rs
  duva/tests/client_ops/test_snapshot_persists_and_recovers_state.rs
  duva/tests/client_ops/test_ttl.rs
  duva/tests/cluster_ops/test_cluster_forget_makes_all_nodes_forget_target_node.rs
  duva/tests/cluster_ops/test_cluster_forget_when_wrong_id_given.rs
  duva/tests/cluster_ops/test_cluster_known_nodes_increase_when_new_replica_is_added.rs
  duva/tests/cluster_ops/test_lazy_discovery.rs
  duva/tests/cluster_ops/test_reconnection_on_reboot.rs
  duva/tests/cluster_ops/test_removes_node_when_heartbeat_is_not_received_for_certain_time.rs
  duva/tests/common.rs
  duva/tests/replication_ops/test_leader_election.rs
  duva/tests/replication_ops/test_raft_happy_case.rs
  duva/tests/replication_ops/test_sync.rs
Labels: testability

#559 feat: log level setting
  Makefile
  duva/src/init.rs
  duva/src/main.rs
  duva/tests/common.rs
Labels: feat

#560 feat: cluster meet outline
  Makefile
  diagrams/clustering.mmd
  diagrams/consistent-hashing-server.mmd
  duva-client/src/controller.rs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/commands/cluster_actor_command.rs
  duva/src/domains/cluster_actors/peer_connections/outbound/stream.rs
  duva/src/domains/operation_logs/logger.rs
  duva/src/domains/query_parsers/query_io.rs
  duva/src/presentation/clients/controller.rs
  duva/src/presentation/clusters/communication_manager.rs
  duva/src/services/handlers/cluster.rs
  duva/tests/cluster_ops/mod.rs
  duva/tests/cluster_ops/test_cluster_meet.rs
  duva/tests/common.rs
Labels: bug, feat

#561 feat: background handshake spawn from inbound stream
  duva/src/domains/caches/actor.rs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/commands/cluster_actor_command.rs
  duva/src/domains/cluster_actors/consensus/election.rs
  duva/src/domains/cluster_actors/listener.rs
  duva/src/domains/cluster_actors/peer_connections/inbound/stream.rs
  duva/src/domains/cluster_actors/peer_connections/outbound/stream.rs
  duva/src/domains/cluster_actors/replication.rs
  duva/src/domains/peers/connected_peer_info.rs
  duva/src/domains/peers/identifier.rs
  duva/src/lib.rs
  duva/src/presentation/clusters/communication_manager.rs
  duva/src/services/handlers/cluster.rs
  duva/tests/cluster_ops/test_cluster_meet.rs
  duva/tests/cluster_ops/test_heartbeat.rs
  duva/tests/replication_ops/test_leader_election.rs
Labels: bug, feat

#564 refactor: ban list handling
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/heartbeats/heartbeat.rs
  duva/src/domains/cluster_actors/listener.rs
  duva/src/domains/cluster_actors/peer_connections/inbound/stream.rs
  duva/src/domains/cluster_actors/peer_connections/outbound/stream.rs
  duva/src/domains/cluster_actors/replication.rs
  duva/src/domains/peers/peer.rs
  duva/src/services/handlers/cluster.rs
  duva/tests/cluster_ops/test_cluster_forget_makes_all_nodes_forget_target_node.rs
Labels: refactoring

#565 remove service layer
  duva-client/src/broker/mod.rs
  duva-client/src/broker/read_stream.rs
  duva/src/adapters/io/tokio_stream.rs
  duva/src/domains/caches/mod.rs
  duva/src/domains/caches/service.rs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/commands/mod.rs
  duva/src/domains/cluster_actors/mod.rs
  duva/src/domains/cluster_actors/service.rs
  duva/src/domains/config_actors/actor.rs
  duva/src/domains/config_actors/mod.rs
  duva/src/domains/config_actors/service.rs
  duva/src/domains/interface.rs
  duva/src/domains/mod.rs
  duva/src/domains/peers/command.rs
  duva/src/domains/peers/connected_types.rs
  duva/src/domains/peers/connections/inbound/mod.rs
  duva/src/domains/peers/connections/inbound/request.rs
  duva/src/domains/peers/connections/inbound/stream.rs
  duva/src/domains/peers/connections/mod.rs
  duva/src/domains/peers/connections/outbound/mod.rs
  duva/src/domains/peers/connections/outbound/response.rs
  duva/src/domains/peers/connections/outbound/stream.rs
  duva/src/domains/peers/mod.rs
  duva/src/domains/peers/peer.rs
  duva/src/domains/peers/service.rs
  duva/src/domains/saves/mod.rs
  duva/src/domains/saves/service.rs
  duva/src/lib.rs
  duva/src/presentation/clients/authenticate.rs
  duva/src/presentation/clients/stream.rs
  duva/src/services/handlers/mod.rs
  duva/src/services/mod.rs
  duva/tests/cluster_ops/test_cluster_forget_makes_all_nodes_forget_target_node.rs
  duva/tests/common.rs
Labels: refactoring

#566 feat: optional rebalancing trigger
  duva-client/src/cli/editor/hints.rs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/commands/command.rs
  duva/src/domains/cluster_actors/commands/mod.rs
  duva/src/domains/cluster_actors/service.rs
  duva/src/presentation/clients/controller.rs
  duva/src/presentation/clients/request.rs
  duva/src/presentation/clusters/communication_manager.rs
Labels: feat

#567 refactor: peer message aggregated for better search
  duva-client/src/broker/mod.rs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/command.rs
  duva/src/domains/cluster_actors/commands/election.rs
  duva/src/domains/cluster_actors/commands/mod.rs
  duva/src/domains/cluster_actors/commands/write_con.rs
  duva/src/domains/cluster_actors/consensus/log.rs
  duva/src/domains/cluster_actors/heartbeat_scheduler.rs
  duva/src/domains/cluster_actors/heartbeats/heartbeat.rs
  duva/src/domains/cluster_actors/heartbeats/mod.rs
  duva/src/domains/cluster_actors/mod.rs
  duva/src/domains/cluster_actors/replication.rs
  duva/src/domains/cluster_actors/service.rs
  duva/src/domains/peers/command.rs
  duva/src/domains/peers/connections/connected_peer_info.rs
  duva/src/domains/peers/connections/connected_types.rs
  duva/src/domains/peers/connections/inbound/stream.rs
  duva/src/domains/peers/connections/mod.rs
  duva/src/domains/peers/connections/outbound/stream.rs
  duva/src/domains/peers/mod.rs
  duva/src/domains/peers/peer.rs
  duva/src/domains/peers/service.rs
  duva/src/domains/query_parsers/query_io.rs
  duva/src/lib.rs
  duva/src/presentation/clients/controller.rs
  duva/src/presentation/clients/request.rs
  duva/src/presentation/clusters/communication_manager.rs
  duva/tests/cluster_ops/test_cluster_forget_makes_all_nodes_forget_target_node.rs
  duva/tests/replication_ops/test_leader_election.rs
  duva/tests/replication_ops/test_raft_happy_case.rs
Labels: refactoring

#568 refactor: peer message integrated with cluster command / test simplification
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/command.rs
  duva/src/domains/cluster_actors/replication.rs
  duva/src/domains/cluster_actors/service.rs
  duva/src/domains/peers/command.rs
  duva/src/domains/peers/mod.rs
  duva/src/domains/peers/service.rs
  duva/src/domains/query_parsers/query_io.rs
  duva/src/presentation/clients/request.rs
  duva/tests/client_ops/test_append.rs
  duva/tests/client_ops/test_config_get_dir.rs
  duva/tests/client_ops/test_decr.rs
  duva/tests/client_ops/test_decrby.rs
  duva/tests/client_ops/test_del.rs
  duva/tests/client_ops/test_exists.rs
  duva/tests/client_ops/test_incr.rs
  duva/tests/client_ops/test_incrby.rs
  duva/tests/client_ops/test_keys.rs
  duva/tests/client_ops/test_replication_info.rs
  duva/tests/client_ops/test_set_get.rs
  duva/tests/client_ops/test_snapshot_persists_and_recovers_state.rs
  duva/tests/client_ops/test_ttl.rs
  duva/tests/cluster_ops/mod.rs
  duva/tests/cluster_ops/test_cluster_forget_makes_all_nodes_forget_target_node.rs
  duva/tests/cluster_ops/test_cluster_forget_when_wrong_id_given.rs
  duva/tests/cluster_ops/test_cluster_known_nodes_increase_when_new_replica_is_added.rs
  duva/tests/cluster_ops/test_cluster_meet.rs
  duva/tests/cluster_ops/test_heartbeat.rs
  duva/tests/cluster_ops/test_lazy_discovery.rs
  duva/tests/cluster_ops/test_reconnection_on_reboot.rs
  duva/tests/cluster_ops/test_removes_node_when_heartbeat_is_not_received_for_certain_time.rs
  duva/tests/common.rs
  duva/tests/replication_ops/test_leader_election.rs
  duva/tests/replication_ops/test_raft_happy_case.rs
  duva/tests/replication_ops/test_sync.rs
Labels: testability, refactoring

#569 refactor: message separation
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/command.rs
  duva/src/domains/cluster_actors/service.rs
  duva/src/presentation/clients/controller.rs
  duva/src/presentation/clusters/communication_manager.rs
Labels: refactoring

#570 refactoring: apply message hirarchy
  duva/src/actor_registry.rs
  duva/src/domains/caches/cache_manager.rs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/command.rs
  duva/src/domains/cluster_actors/heartbeat_scheduler.rs
  duva/src/domains/cluster_actors/replication.rs
  duva/src/domains/cluster_actors/service.rs
  duva/src/domains/peers/connections/inbound/stream.rs
  duva/src/domains/peers/connections/outbound/stream.rs
  duva/src/domains/peers/service.rs
  duva/src/domains/saves/actor.rs
  duva/src/domains/saves/endec/decoder.rs
  duva/src/domains/saves/endec/encoder.rs
  duva/src/domains/saves/snapshot/mod.rs
  duva/src/domains/saves/snapshot/snapshot_loader.rs
  duva/src/init.rs
  duva/src/lib.rs
  duva/src/presentation/clients/controller.rs
  duva/src/presentation/clusters/communication_manager.rs
Labels: refactoring

#571 refactor: fmt rule
  duva-client/src/broker/mod.rs
  duva-client/src/broker/read_stream.rs
  duva-client/src/broker/write_stream.rs
  duva-client/src/cli/editor/completion.rs
  duva-client/src/cli/main.rs
  duva-client/src/controller.rs
  duva/src/adapters/io/tokio_stream.rs
  duva/src/adapters/op_logs/disk_based.rs
  duva/src/domains/caches/cache_manager.rs
  duva/src/domains/caches/service.rs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/command.rs
  duva/src/domains/cluster_actors/consensus/election.rs
  duva/src/domains/cluster_actors/heartbeat_scheduler.rs
  duva/src/domains/cluster_actors/replication.rs
  duva/src/domains/cluster_actors/service.rs
  duva/src/domains/config_actors/config_manager.rs
  duva/src/domains/config_actors/service.rs
  duva/src/domains/operation_logs/operation.rs
  duva/src/domains/peers/command.rs
  duva/src/domains/peers/connections/connected_peer_info.rs
  duva/src/domains/peers/connections/inbound/request.rs
  duva/src/domains/peers/connections/outbound/response.rs
  duva/src/domains/peers/connections/outbound/stream.rs
  duva/src/domains/peers/identifier.rs
  duva/src/domains/peers/peer.rs
  duva/src/domains/query_parsers/query_io.rs
  duva/src/domains/saves/actor.rs
  duva/src/domains/saves/endec/decoder.rs
  duva/src/domains/saves/endec/mod.rs
  duva/src/domains/saves/service.rs
  duva/src/lib.rs
  duva/src/presentation/clients/authenticate.rs
  duva/src/presentation/clients/controller.rs
  duva/src/presentation/clients/request.rs
  duva/src/presentation/clients/stream.rs
  duva/tests/common.rs
  rustfmt.toml
Labels: refactoring

#572 refactor: encapsulate logger
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/service.rs
  duva/src/domains/cluster_actors/session.rs
  duva/src/domains/operation_logs/logger.rs
  duva/src/lib.rs
Labels: enhancement, refactoring

#573 refactor: subsplit handler, manage visibility
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/service.rs
  duva/src/domains/peers/connections/inbound/stream.rs
Labels: refactoring

#574 feat: logging made on cluster actor
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/service.rs
  duva/src/domains/peers/service.rs
  duva/src/main.rs
Labels: enhancement

#576 chore: hash-ring required input
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/command.rs
  duva/src/domains/cluster_actors/hash_ring.rs
  duva/src/domains/peers/service.rs
  duva/src/presentation/clients/controller.rs
Labels: feat

#578 feat : hash ring set up
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/hash_ring.rs
  duva/src/domains/cluster_actors/replication.rs
Labels: enhancement, refactoring

#579 chore: wrapper on cache sender
  duva/src/domains/caches/actor.rs
  duva/src/domains/caches/service.rs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/hash_ring.rs
Labels: chore

#580 feat: last modified added to hash ring
  duva/src/domains/cluster_actors/hash_ring.rs
Labels: feat

#581 chore: last_modified value on `HashRing` changed
  duva/src/domains/cluster_actors/hash_ring.rs
Labels: chore

#587 refactor: clean up peer list exchange
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/hash_ring.rs
  duva/src/domains/cluster_actors/replication.rs
  duva/src/domains/cluster_actors/service.rs
  duva/src/domains/peers/connections/connected_peer_info.rs
  duva/src/domains/peers/connections/connected_types.rs
  duva/src/domains/peers/connections/inbound/stream.rs
  duva/src/domains/peers/connections/outbound/response.rs
  duva/src/domains/peers/connections/outbound/stream.rs
Labels: refactoring

#588 feat: edge cases covered for rebalance initiation process
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/peers/connections/connected_types.rs
  duva/src/domains/peers/connections/connection_types.rs
  duva/src/domains/peers/connections/inbound/stream.rs
  duva/src/domains/peers/connections/mod.rs
  duva/src/domains/peers/connections/outbound/stream.rs
  duva/src/domains/peers/peer.rs
  duva/src/domains/peers/service.rs
Labels: bug, feat

#592 docs: readme
  README.md
  duva/src/domains/operation_logs/logger.rs
Labels: documentation
