Repository Migorithm/duva, pull requests merged in 2025-06, with the labels that each got.

#593 LRU implements for cache db
  duva/src/domains/caches/actor.rs
  duva/src/domains/caches/cache_db.rs
  duva/src/domains/caches/mod.rs
  duva/src/domains/caches/service.rs
Labels: enhancement

#598 Implement LRU implements for cache db
  duva/src/domains/caches/actor.rs
  duva/src/domains/caches/cache_db.rs
  duva/src/domains/caches/cache_db/cache_node.rs
  duva/src/domains/caches/cache_db/entry.rs
  duva/src/domains/caches/cache_db/iter.rs
  duva/src/domains/caches/cache_db/tests.rs
  duva/src/domains/caches/mod.rs
  duva/src/domains/caches/service.rs
Labels: bug

#599 docs: lru
  Cargo.lock
  README.md
  docs/_posts/2025-06-02-lru.md
  duva/Cargo.toml
Labels: documentation

#596 feat: make migration plan
  diagrams/consistent-hashing-server.mmd
  duva/src/domains/caches/cache_db.rs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/actor/client_sessions.rs
  duva/src/domains/cluster_actors/actor/heartbeat_scheduler.rs
  duva/src/domains/cluster_actors/actor/tests/cluster_managements.rs
  duva/src/domains/cluster_actors/actor/tests/elections.rs
  duva/src/domains/cluster_actors/actor/tests/mod.rs
  duva/src/domains/cluster_actors/actor/tests/partitionings.rs
  duva/src/domains/cluster_actors/actor/tests/replications.rs
  duva/src/domains/cluster_actors/command.rs
  duva/src/domains/cluster_actors/consensus/log.rs
  duva/src/domains/cluster_actors/hash_ring.rs
  duva/src/domains/cluster_actors/hash_ring/hash_func.rs
  duva/src/domains/cluster_actors/hash_ring/tests/add_and_remove.rs
  duva/src/domains/cluster_actors/hash_ring/tests/migration.rs
  duva/src/domains/cluster_actors/hash_ring/tests/mod.rs
  duva/src/domains/cluster_actors/mod.rs
  duva/src/domains/cluster_actors/service.rs
  duva/src/domains/cluster_actors/tests/partitionings.rs
  duva/src/lib.rs
  duva/src/presentation/clients/request.rs
  duva/src/presentation/clients/stream.rs
Labels: testability, feat

#600 feat: revisit keys for reusability
  duva/src/domains/caches/actor.rs
  duva/src/domains/caches/cache_db.rs
  duva/src/domains/caches/cache_db/cache_node.rs
  duva/src/domains/caches/cache_manager.rs
  duva/src/domains/caches/command.rs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/hash_ring.rs
  duva/src/domains/cluster_actors/hash_ring/migration_task.rs
  duva/src/presentation/clients/controller.rs
Labels: feat

#602 feat: lru slab based implementation
  docs/_posts/2025-06-04-slab-based-lru.md
  duva/src/domains/caches/actor.rs
  duva/src/domains/caches/cache_db.rs
  duva/src/domains/caches/cache_db/cache_node.rs
  duva/src/domains/caches/cache_db/entry.rs
  duva/src/domains/caches/cache_db/iter.rs
  duva/src/domains/caches/cache_db/tests.rs
  duva/src/domains/caches/cache_objects.rs
  duva/src/domains/caches/lru_cache.rs
  duva/src/domains/caches/mod.rs
  duva/src/domains/caches/service.rs
  duva/src/domains/cluster_actors/actor.rs
Labels: feat

#612 feat: bulk delete consensus, lazy unblocking, state reflection
  diagrams/consistent-hashing-server.mmd
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/actor/tests/mod.rs
  duva/src/domains/cluster_actors/actor/tests/partitionings.rs
  duva/src/domains/cluster_actors/command.rs
  duva/src/domains/cluster_actors/hash_ring/migration_task.rs
  duva/src/domains/cluster_actors/service.rs
  duva/src/domains/peers/connections/inbound/stream.rs
  duva/tests/replication_ops/test_leader_election.rs
Labels: bug, testability, feat

#618 feat: set consensus on rebalancing
  duva/src/domains/caches/cache_manager.rs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/actor/tests/mod.rs
  duva/src/domains/cluster_actors/actor/tests/partitionings.rs
  duva/src/domains/cluster_actors/command.rs
  duva/src/domains/cluster_actors/service.rs
  duva/src/domains/operation_logs/operation.rs
  duva/src/domains/peers/command.rs
Labels: bug, feat

#620 feat: Separate leader and replica responsibilities in hash ring updates
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/actor/tests/partitionings.rs
Labels: bug, refactoring, feat

#622 docs: feat-608 diagram, design proposal
  diagrams/hash-updating-strategy-prop1.mmd
  diagrams/hash-updating-strategy-prop2.mmd
Labels: documentation

#627 fix: client hang after election
  duva/src/domains/cluster_actors/actor/tests/replications.rs
  duva/src/domains/cluster_actors/consensus/log.rs
Labels: bug

#628 test: get_required_votes
  duva/src/domains/cluster_actors/consensus/log.rs
Labels: testability

#631 test: more assertions on migration
  duva/tests/cluster_ops/test_cluster_meet.rs
Labels: testability

#632 refactor: leader requests consensus
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/actor/tests/replications.rs
  duva/src/domains/cluster_actors/command.rs
  duva/src/domains/cluster_actors/service.rs
  duva/tests/cluster_ops/test_cluster_forget_when_wrong_id_given.rs
Labels: testability, refactoring

#633 chore: remove bulkset
  duva/src/domains/caches/cache_manager.rs
Labels: refactoring

#634 chore: minor refactoring
  duva/src/domains/caches/cache_manager.rs
  duva/src/domains/cluster_actors/actor.rs
Labels: chore

#638 docs: MGET, partitioning
  README.md
Labels: documentation

#640 refactor: simplify presentation logic
  duva/src/presentation/clients/mod.rs
  duva/src/presentation/clients/parser.rs
  duva/src/presentation/clients/stream.rs
Labels: refactoring

#648 feat: leadership information propagation through gossip
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/actor/tests/cluster_managements.rs
  duva/src/domains/cluster_actors/actor/tests/elections.rs
  duva/src/domains/cluster_actors/actor/tests/mod.rs
  duva/src/domains/cluster_actors/replication.rs
  duva/src/domains/peers/connections/connection_types.rs
  duva/src/domains/peers/connections/inbound/request.rs
  duva/src/domains/peers/connections/inbound/stream.rs
  duva/src/domains/peers/connections/outbound/stream.rs
  duva/src/domains/peers/peer.rs
  duva/src/domains/query_io.rs
  duva/src/presentation/clients/controller.rs
  duva/tests/common.rs
  duva/tests/replication_ops/test_leader_election.rs
Labels: testability, refactoring, feat

#653 optimization: box hashring on message
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/actor/tests/partitionings.rs
  duva/src/domains/peers/command.rs
  duva/src/domains/query_io.rs
  duva/tests/cluster_ops/test_cluster_meet.rs
  duva/tests/common.rs
Labels: enhancement

#654 feat: kill node kind
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/actor/tests/cluster_managements.rs
  duva/src/domains/cluster_actors/actor/tests/elections.rs
  duva/src/domains/cluster_actors/actor/tests/mod.rs
  duva/src/domains/cluster_actors/actor/tests/partitionings.rs
  duva/src/domains/cluster_actors/replication.rs
  duva/src/domains/peers/connections/connection_types.rs
  duva/src/domains/peers/peer.rs
  duva/src/domains/query_io.rs
  duva/src/lib.rs
  duva/tests/cluster_ops/test_lazy_discovery.rs
  duva/tests/common.rs
Labels: bug, testability, refactoring, kill legacy

#655 chore: rename, encapsulate id
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/operation_logs/operation.rs
  duva/src/domains/peers/connections/inbound/stream.rs
  duva/src/domains/peers/connections/outbound/stream.rs
  duva/src/domains/peers/peer.rs
  duva/src/lib.rs
Labels: refactoring

#656 refactor join_peer_network_if_absent
  duva/src/domains/cluster_actors/actor.rs
Labels: refactoring

#658 feat: hashring multi shard leader update
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/actor/tests/cluster_managements.rs
  duva/src/domains/cluster_actors/actor/tests/elections.rs
  duva/src/domains/cluster_actors/actor/tests/mod.rs
  duva/src/domains/cluster_actors/actor/tests/partitionings.rs
  duva/src/domains/cluster_actors/hash_ring.rs
  duva/src/domains/cluster_actors/hash_ring/tests/add_and_remove.rs
  duva/src/domains/cluster_actors/hash_ring/tests/migration.rs
  duva/src/domains/cluster_actors/hash_ring/tests/mod.rs
  duva/src/domains/cluster_actors/service.rs
  duva/src/domains/peers/peer.rs
  duva/src/domains/query_io.rs
Labels: testability, refactoring, feat

#660 feat: reshard
  duva/src/domains/cluster_actors/service.rs
  duva/src/presentation/clients/request.rs
  duva/tests/replication_ops/test_leader_election.rs
Labels: testability, refactoring, feat

#665 docs: remove unncessary diagrams on clustering
  README.md
  diagrams/clustering.mmd
Labels: documentation

#667 test: increased volume on keys for cluster migration
  duva/tests/cluster_ops/test_cluster_meet.rs
  duva/tests/cluster_ops/test_lazy_discovery.rs
  duva/tests/common.rs
Labels: testability

#668 feat: synchronized topology file
  duva/src/config.rs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/actor/tests/cluster_managements.rs
  duva/src/domains/cluster_actors/actor/tests/mod.rs
  duva/src/domains/cluster_actors/service.rs
  duva/src/lib.rs
Labels: feat

#669 refactor: simplify election state
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/consensus/election.rs
  duva/src/domains/cluster_actors/replication.rs
Labels: refactoring

#670 refactor: replication ack revisited
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/actor/tests/mod.rs
  duva/src/domains/cluster_actors/actor/tests/replications.rs
  duva/src/domains/peers/command.rs
  duva/src/domains/query_io.rs
Labels: refactoring

#671 feat: hashring based on current shard leaders
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/actor/tests/cluster_managements.rs
  duva/src/domains/cluster_actors/actor/tests/partitionings.rs
  duva/src/domains/cluster_actors/hash_ring.rs
  duva/src/domains/cluster_actors/hash_ring/tests/add_and_remove.rs
  duva/src/domains/cluster_actors/hash_ring/tests/migration.rs
  duva/src/domains/query_io.rs
Labels: testability, refactoring, feat

#681 refactor: async removed from ReplicatedLogs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/actor/tests/elections.rs
  duva/src/domains/cluster_actors/actor/tests/replications.rs
  duva/src/domains/operation_logs/logger.rs
Labels: enhancement, refactoring

#683 fix: apply optimistic migration, resolve hashring update timing issue
  diagrams/consistent-hashing-server.mmd
  duva-client/src/broker/mod.rs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/actor/tests/partitionings.rs
Labels: bug, testability, refactoring, feat

#684 feat: better logging strategy
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/actor/tests/partitionings.rs
  duva/src/domains/cluster_actors/service.rs
  duva/src/macros.rs
Labels: refactoring, feat

#686 refactor: error, file logging
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/actor/tests/elections.rs
  duva/src/domains/cluster_actors/actor/tests/partitionings.rs
  duva/src/domains/cluster_actors/service.rs
  duva/src/macros.rs
Labels: enhancement, refactoring

#687 fix : test on leader election
  duva/src/adapters/op_logs/disk_based.rs
  duva/src/domains/cluster_actors/hash_ring.rs
  duva/tests/replication_ops/test_leader_election.rs
Labels: testability

#688 chore: let chain applied
  duva-client/src/broker/mod.rs
  duva-client/src/broker/write_stream.rs
  duva-client/src/cli/editor/hints.rs
  duva-client/src/cli/main.rs
  duva-client/src/controller.rs
  duva/benches/benchmark_cache_db.rs
  duva/benches/benchmark_query.rs
  duva/src/adapters/io/tokio_stream.rs
  duva/src/adapters/op_logs/disk_based.rs
  duva/src/config.rs
  duva/src/domains/caches/cache_manager.rs
  duva/src/domains/caches/lru_cache.rs
  duva/src/domains/cluster_actors/actor/tests/cluster_managements.rs
  duva/src/domains/cluster_actors/actor/tests/mod.rs
  duva/src/domains/cluster_actors/hash_ring.rs
  duva/src/domains/cluster_actors/hash_ring/tests/add_and_remove.rs
  duva/src/domains/cluster_actors/hash_ring/tests/migration.rs
  duva/src/domains/cluster_actors/hash_ring/tests/mod.rs
  duva/src/domains/cluster_actors/replication.rs
  duva/src/domains/peers/connections/inbound/request.rs
  duva/src/domains/peers/connections/inbound/stream.rs
  duva/src/domains/peers/connections/outbound/response.rs
  duva/src/domains/peers/identifier.rs
  duva/src/domains/peers/peer.rs
  duva/src/domains/query_io.rs
  duva/src/domains/saves/endec/decoder.rs
  duva/src/domains/saves/endec/encoder.rs
  duva/src/domains/saves/service.rs
  duva/src/lib.rs
  duva/src/macros.rs
  duva/src/presentation/clusters/communication_manager.rs
  duva/tests/client_ops/test_keys.rs
  duva/tests/client_ops/test_snapshot_persists_and_recovers_state.rs
  duva/tests/cluster_ops/test_cluster_meet.rs
  duva/tests/common.rs
  duva/tests/replication_ops/test_leader_election.rs
Labels: enhancement

#692 enhancement: optimize LTO
  duva-client/Cargo.toml
  duva/Cargo.toml
Labels: enhancement

#694 feat: 693 -> stored value from String to Bytes
  duva-client/src/broker/mod.rs
  duva-client/src/controller.rs
  duva/Cargo.toml
  duva/benches/benchmark.rs
  duva/benches/benchmark_cache_db.rs
  duva/benches/benchmark_query.rs
  duva/src/domains/caches/actor.rs
  duva/src/domains/caches/cache_manager.rs
  duva/src/domains/caches/cache_objects.rs
  duva/src/domains/caches/lru_cache.rs
  duva/src/domains/cluster_actors/actor.rs
  duva/src/domains/cluster_actors/actor/tests/mod.rs
  duva/src/domains/peers/connections/inbound/request.rs
  duva/src/domains/peers/connections/inbound/stream.rs
  duva/src/domains/peers/connections/outbound/stream.rs
  duva/src/domains/query_io.rs
  duva/src/domains/saves/endec/decoder.rs
  duva/src/domains/saves/endec/encoder.rs
  duva/src/presentation/clients/controller.rs
  duva/src/presentation/clients/stream.rs
  duva/tests/common.rs
Labels: enhancement, refactoring
